/* ValueGrid v2 — refined map app */
import { WORLD } from './world.js';
import { COMPANIES, FLOWS, STATE_SHARES, FLOW_VINTAGE } from './data.js';
// Namespace import: facts.js is regenerated by scripts/fetch-data.mjs and may
// predate the MCAPS/MCAP_ASOF/YEAR_MULT exports — a named import of a missing
// binding would be a hard SyntaxError, this degrades gracefully instead.
import * as GEN from './facts.js';
const FACTS=GEN.FACTS, MCAPS=GEN.MCAPS||{}, MCAP_ASOF=GEN.MCAP_ASOF||null, YEAR_MULT=GEN.YEAR_MULT||{};
import { PERIODS } from './years.js';
import { RENTS, ARCHIVE, CATS, BARS, BARWHY, RENT_ASOF, rMult, rentScore, rentProv, rTrend, rRun, rVol, rSubs, rBars, rVolume } from './rents.js';
import { MICRO, MCATS, MCAT, MBARS, MBARWHY, MICRO_ASOF, mMult, mPayback, microScore, microProv, mVolume } from './micro.js';

const C=COMPANIES, FL=FLOWS;
const byId=Object.fromEntries(C.map(c=>[c.id,c]));
const SEC={tech:'#5b8cff',fin:'#2dd4e8',energy:'#f5b042',health:'#3fd68a',cons:'#f472b6',ind:'#a78bfa',gov:'#e2e8f0',telecom:'#00d9ff',materials:'#ed8f00',utilities:'#1fb979'};
const SECNAME={tech:'Technology',fin:'Finance',energy:'Energy',health:'Healthcare',cons:'Consumer',ind:'Industrials',gov:'Government / Central Bank',telecom:'Telecommunications',materials:'Materials',utilities:'Utilities'};
const PCOL={R:'#3fd68a',E:'#f5b042',I:'#ff6b7a'}, PNAME={R:'Reported',E:'Estimated',I:'Inferred'};
const CB=new Set(['FED','ECB','PBOC','BOJ']); // central banks: their scale figure is a balance-sheet stock, not an annual flow
// Per-year global multiplier vs the flow-vintage year. 2019–2023 are the
// original curated estimates AND are ratios against FLOW_VINTAGE '2024' —
// if the vintage ever moves, this table must be re-derived, not kept. Later
// years come from YEAR_MULT (computed by the fetch pipeline from aggregate
// SEC-reported revenue growth). The vintage year itself is structurally 1.
const VINTAGE=String(FLOW_VINTAGE);
const TMUL_HIST={2019:.62,2020:.60,2021:.82,2022:.95,2023:.97};
const TMUL=PERIODS.map(p=>p===VINTAGE?1:TMUL_HIST[p]??YEAR_MULT[p]??1);
let sizeBy='mcap',secOn={},layerOn={R:1,E:1,I:1},tIdx=PERIODS.length-1,playing=false,live=false,selected=null,hover=null;
Object.keys(SEC).forEach(s=>secOn[s]=1);
const fmt=v=>v>=1000?'$'+(v/1000).toFixed(2)+'T':(v>=1?'$'+v.toFixed(0)+'B':'$'+(v*1000).toFixed(0)+'M');
// HTML-escape for data strings interpolated into innerHTML templates. The
// dataset is curated, but names legitimately contain '&' and this keeps any
// future data edit from becoming a markup injection.
const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
// Revenue for the current period: real SEC-reported series where we have one
// (FACTS, generated from XBRL filings), otherwise the curated base figure
// scaled by the global year multiplier — an estimate, and labeled as such.
const hasFact=c=>{const f=FACTS[c.id];return !!(f&&f.revT&&f.revT[PERIODS[tIdx]]!=null);};
const revAt=c=>hasFact(c)?FACTS[c.id].revT[PERIODS[tIdx]]:c.rev*TMUL[tIdx];
// Display provenance: a node only earns the "Reported" tag when the figure for
// the CURRENTLY SELECTED year is backed by a filing — a series with a gap year
// degrades to E while scrubbed onto the gap, matching what revAt displays.
const nProv=c=>hasFact(c)?'R':(c.prov==='R'?'E':c.prov);
// Market cap for display: the generated value (price × shares outstanding,
// dated MCAP_ASOF) when the pipeline produced one, else the curated fallback.
// Macro-node checks (c.mcap===0 / c.mcap>0) stay on the raw curated field.
const mcapOf=c=>(MCAPS[c.id]&&MCAPS[c.id].v)||c.mcap;
// Flow display provenance: flow values are anchored to the vintage year and
// scaled by the global multiplier when scrubbed — so off the anchor year even
// a "Reported" flow is showing an estimate, and must degrade to E on screen.
// String() tolerates a numeric FLOW_VINTAGE; membership in PERIODS is
// enforced by a unit test (the refresh workflow's deploy gate), since an
// out-of-axis vintage would make this -1 and break provenance display.
const ANCHOR=PERIODS.indexOf(VINTAGE);
const fProv=e=>(e.p==='R'&&tIdx!==ANCHOR)?'E':e.p;
// Flow kind: derived from the methodology string when the data doesn't carry an
// explicit `k` field — 446/478 flows map mechanically from their source strings.
const KIND_PATTERNS=[
  [/Tax-incidence model/i,'tax'],
  [/household demand share/i,'household'],
  [/banking\/credit relationship/i,'banking'],
  [/energy.intensity|Energy I-O/i,'energy'],
  [/dividend\/distribution/i,'dividend'],
  [/social benefits|social transfers|social protection/i,'govt_transfer'],
  [/Household.*tax|income tax.*receipts|social.*contributions/i,'govt_tax'],
  [/central.bank|SOMA|FX profits|payment to the national/i,'central_bank'],
  [/government sales|gov.*procurement|USAspending/i,'govt_procurement'],
  [/wages and benefits/i,'wage'],
  [/foundry.*BOM|leading-edge silicon/i,'foundry'],
  [/supplier.concentration|supply.*chain|COGS|procurement|battery.*sourcing|component.*supply|assembly.*manufacturing/i,'supply'],
  [/interchange.*settlement|payment.*network/i,'payment_net'],
  [/search.*placement|Traffic.*acquisition/i,'tac'],
  [/cloud infrastructure.*spend/i,'cloud_spend'],
  [/FX profits.*transfer/i,'central_bank'],
];
const kindOf=e=>e.k||KIND_PATTERNS.find(([re])=>re.test(e.m))?.[1]||'other';
const KIND_LABEL={tax:'Corporate tax',household:'Household demand',banking:'Banking/credit',energy:'Energy input',dividend:'Dividends',govt_transfer:'Govt transfers',govt_tax:'Household taxes',central_bank:'Central bank',govt_procurement:'Govt procurement',wage:'Wages',foundry:'Foundry spend',supply:'Supply chain',payment_net:'Payment network',tac:'Traffic acquisition',cloud_spend:'Cloud spend',other:'Other'};
// Respect the OS "reduce motion" setting: freeze the travelling flow-dot pulse.
const reduceMotion=!!(window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches);

/* ---- projection (equirectangular w/ smooth view) ---- */
const map=document.getElementById('map'),mx=map.getContext('2d');
let MW=0,MH=0;
// Clamp the device-pixel-ratio: canvas fill cost scales with DPR^2, so an
// uncapped 3x display did ~9x the raster work. 2x keeps it crisp without the cliff.
let DPR=Math.min(window.devicePixelRatio||1,2);
let view={cx:10,cy:25,scale:1}, target={cx:10,cy:25,scale:1};
function pxPerDeg(){return (MW/360)*view.scale;}
function proj(lon,lat){const s=pxPerDeg();return{x:MW/2+(lon-view.cx)*s, y:MH/2-(lat-view.cy)*s*0.95};}
function unproj(x,y){const s=pxPerDeg();return{lon:view.cx+(x-MW/2)/s, lat:view.cy-(y-MH/2)/(s*0.95)};}

/* ---- filtered data ---- */
// The selected node always stays visible even if its sector is toggled off
// (search can select any node, so its pin must exist to anchor the view).
// nodeVis is the single visibility rule shared by the map AND the inspector,
// so the inspector's flow lists always agree with the arcs actually drawn.
const nodeVis=c=>secOn[c.sec]||c.id===selected;
const visC=()=>C.filter(nodeVis);
const visF=()=>{const m=TMUL[tIdx];return FL.filter(e=>layerOn[e.p]&&byId[e.f]&&byId[e.t]&&nodeVis(byId[e.f])&&nodeVis(byId[e.t])).map(e=>({...e,vv:e.v*m}));};

/* ---- rendering ---- */
let pulse=0,t0=performance.now(),lastDrawn=[];
function frame(now){
  const dt=Math.min(2,(now-t0)/16.7);t0=now;
  // ease view toward target
  view.cx+=(target.cx-view.cx)*0.16*dt; view.cy+=(target.cy-view.cy)*0.16*dt; view.scale+=(target.scale-view.scale)*0.16*dt;
  // clamp center to keep map on-screen (limits widen with zoom)
  target.cx=Math.max(-200,Math.min(200,target.cx)); target.cy=Math.max(-88,Math.min(95,target.cy));
  view.cx=Math.max(-220,Math.min(220,view.cx)); view.cy=Math.max(-92,Math.min(98,view.cy));
  pulse=(pulse+(reduceMotion?0:(live?0.018:0.008))*dt)%1;
  render();
  mapRAF=requestAnimationFrame(frame);
}
// The map loop is suspended entirely while the Scarcity tab is showing — the
// canvas is display:none, so every frame would be pure waste.
let mapRAF=null;
function startMapLoop(){if(mapRAF===null){t0=performance.now();mapRAF=requestAnimationFrame(frame);}}
function stopMapLoop(){if(mapRAF!==null){cancelAnimationFrame(mapRAF);mapRAF=null;}}
function render(){
  DPR=Math.min(window.devicePixelRatio||1,2);
  // Only reallocate the canvas backing store when the size actually changes —
  // reassigning width/height every frame forces a needless clear + GPU realloc.
  const cw=Math.round(map.clientWidth*DPR), ch=Math.round(map.clientHeight*DPR);
  if(MW!==cw||MH!==ch){MW=map.width=cw;MH=map.height=ch;map.style.width='100%';map.style.height='100%';}
  mx.setTransform(1,0,0,1,0,0);
  // bg
  mx.clearRect(0,0,MW,MH);
  // graticule
  mx.strokeStyle='rgba(90,120,170,.08)';mx.lineWidth=1;
  for(let lon=-180;lon<=180;lon+=20){const a=proj(lon,85),b=proj(lon,-85);mx.beginPath();mx.moveTo(a.x,a.y);mx.lineTo(b.x,b.y);mx.stroke();}
  for(let lat=-60;lat<=80;lat+=20){const a=proj(-180,lat),b=proj(180,lat);mx.beginPath();mx.moveTo(a.x,a.y);mx.lineTo(b.x,b.y);mx.stroke();}
  // land (real coastlines)
  mx.lineWidth=1*DPR;
  WORLD.forEach(r=>{
    mx.beginPath();
    for(let i=0;i<r.length;i+=2){const p=proj(r[i],r[i+1]);i?mx.lineTo(p.x,p.y):mx.moveTo(p.x,p.y);}
    mx.closePath();
    mx.fillStyle='#142036';mx.fill();
    mx.strokeStyle='#27375a';mx.stroke();
  });
  const fl=visF();
  // arcs
  fl.forEach(e=>{
    const A=byId[e.f],B=byId[e.t];
    // Antimeridian: route trans-Pacific flows the short way (shift the far
    // endpoint ±360°) instead of dragging the arc across the whole Atlantic.
    let bLng=B.lng; if(Math.abs(bLng-A.lng)>180)bLng+=bLng<A.lng?360:-360;
    const a=proj(A.lng,A.lat),b=proj(bLng,B.lat);
    const hot=selected&&(e.f===selected||e.t===selected);
    // Selection focuses its ego-network but keeps the rest of the graph
    // faintly visible — hiding it entirely made "the map only has 3 flows"
    // a common misread, since boot auto-selects a node.
    const dim=selected&&!hot;
    const fp=fProv(e),col=PCOL[fp];
    const dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1,lift=Math.min(180*DPR,len*0.3);
    const mxp=(a.x+b.x)/2,myp=(a.y+b.y)/2,cx=mxp-dy/len*lift,cy=myp+dx/len*lift-lift*0.3;
    mx.globalAlpha=hot?0.95:dim?0.09:0.34;
    mx.setLineDash(fp==='R'?[]:(fp==='E'?[8*DPR,6*DPR]:[2*DPR,7*DPR]));
    mx.lineWidth=Math.max(1,Math.log(e.vv+1)*0.6)*(hot?1.7:1)*DPR;
    if(hot){mx.shadowBlur=12*DPR;mx.shadowColor=col;}
    mx.strokeStyle=col;mx.beginPath();mx.moveTo(a.x,a.y);mx.quadraticCurveTo(cx,cy,b.x,b.y);mx.stroke();
    mx.shadowBlur=0;mx.setLineDash([]);
    if(hot||!selected){const t=(pulse+(e.f.charCodeAt(0)%9)/9)%1;const q=quad(a,{x:cx,y:cy},b,t);
      mx.globalAlpha=hot?1:0.55;mx.fillStyle=col;if(hot){mx.shadowBlur=8*DPR;mx.shadowColor=col;}
      mx.beginPath();mx.arc(q.x,q.y,(hot?3:2)*DPR,0,6.28);mx.fill();mx.shadowBlur=0;
      if(hot){const q2=quad(a,{x:cx,y:cy},b,0.97);arrow(q2,b,col);}}
  });
  mx.globalAlpha=1;
  // pins. Radius shrinks as you zoom in so dense clusters reveal separation
  // instead of overlapping into a blob.
  const sized=visC();
  // mcap sizing for listed companies; revenue sizing is time-aware (real SEC
  // series where available). Macro nodes (mcap 0) always size by flow scale.
  const sizeVal=c=>(sizeBy==='mcap'&&c.mcap>0)?mcapOf(c):revAt(c);
  const maxV=Math.max(1,...sized.map(sizeVal));
  const zoomShrink=Math.max(0.35, Math.min(1, 1.6/Math.sqrt(view.scale))); // 1 at scale~2.5, ~0.35 floor
  const drawn=[];
  sized.slice().sort((p,q)=>sizeVal(q)-sizeVal(p)).forEach(c=>{
    const s=proj(c.lng,c.lat);
    if(s.x<-60||s.x>MW+60||s.y<-60||s.y>MH+60)return;
    const r=(4+Math.sqrt(sizeVal(c)/maxV)*26)*DPR*zoomShrink;
    drawn.push({c,x:s.x,y:s.y,ox:s.x,oy:s.y,r});
  });
  // collision relaxation: always keep pins from overlapping into a blob, at
  // every zoom level. Pins settle near their true coordinates but never cover
  // each other, so dense clusters stay readable whether zoomed out or in.
  for(let pass=0;pass<8;pass++){
    for(let i=0;i<drawn.length;i++)for(let j=i+1;j<drawn.length;j++){
      const a=drawn[i],b=drawn[j];let dx2=b.x-a.x,dy2=b.y-a.y,d=Math.hypot(dx2,dy2)||0.01;
      const want=(a.r+b.r)*0.62+6*DPR;
      if(d<want){const push=(want-d)/2;const ux=dx2/d,uy=dy2/d;a.x-=ux*push;a.y-=uy*push;b.x+=ux*push;b.y+=uy*push;}
    }
  }
  // tether back toward true location; at high zoom the tether nearly releases
  // so coincident companies fan out into a readable cluster instead of stacking.
  const tether=Math.max(0.015, 0.12/Math.max(1,view.scale*0.6));
  drawn.forEach(p=>{p.x+=(p.ox-p.x)*tether;p.y+=(p.oy-p.y)*tether;});
  lastDrawn=drawn;
  // draw connector when a pin was nudged, then big pins first, small on top
  drawn.forEach(p=>{const dd=Math.hypot(p.x-p.ox,p.y-p.oy);if(dd>p.r*0.8){mx.strokeStyle='rgba(255,255,255,.18)';mx.lineWidth=1*DPR;mx.beginPath();mx.moveTo(p.ox,p.oy);mx.lineTo(p.x,p.y);mx.stroke();}});
  drawn.slice().reverse().forEach(({c,x,y,r})=>{const s={x,y};
    const sel=c.id===selected,hov=hover&&hover.id===c.id;
    const isGov=c.sec==='gov'||c.mcap===0; // governments, central banks, household sectors
    function shape(rr){if(isGov){mx.moveTo(s.x,s.y-rr);mx.lineTo(s.x+rr,s.y);mx.lineTo(s.x,s.y+rr);mx.lineTo(s.x-rr,s.y);mx.closePath();}else{mx.arc(s.x,s.y,rr,0,6.28);}}
    // glow
    if(sel||hov){mx.beginPath();shape(r+8*DPR);const g=mx.createRadialGradient(s.x,s.y,r,s.x,s.y,r+10*DPR);g.addColorStop(0,SEC[c.sec]+'66');g.addColorStop(1,SEC[c.sec]+'00');mx.fillStyle=g;mx.fill();}
    mx.beginPath();shape(r);
    mx.fillStyle=SEC[c.sec];mx.globalAlpha=sel?1:(selected?0.4:0.82);
    if(!selected||sel){mx.shadowBlur=(sel||hov?14:6)*DPR;mx.shadowColor=SEC[c.sec];}
    mx.fill();mx.shadowBlur=0;mx.globalAlpha=1;
    mx.lineWidth=(sel||hov?2.2:1.2)*DPR;mx.strokeStyle=sel||hov?'#fff':'rgba(255,255,255,.55)';mx.stroke();
    // provenance marker (shape + color encode the tier)
    const np2=nProv(c);
    mx.fillStyle=PCOL[np2];mx.strokeStyle='#0a0e16';mx.lineWidth=1.3*DPR;
    provDot(mx,s.x+r*0.7,s.y-r*0.7,3.2*DPR,np2);
  });
  // Label pass — drawn biggest-first; skip a label whose box overlaps an already
  // -placed one (selected/hovered always win), and paint a dark halo so labels
  // stay legible over dense clusters instead of smearing into each other.
  const placed=[];mx.textAlign='center';mx.lineJoin='round';
  drawn.forEach(({c,x,y,r})=>{
    const sel=c.id===selected,hov=hover&&hover.id===c.id;
    if(!(r>15*DPR||sel||hov||view.scale>=4))return;
    const fs=11*DPR;mx.font=(sel||hov?'700 ':'600 ')+fs+'px Inter,-apple-system,Segoe UI,Roboto,sans-serif';
    const w=mx.measureText(c.id).width,lx=x,ly=y+r+13*DPR;
    const box={x:lx-w/2-2*DPR,y:ly-fs,w:w+4*DPR,h:fs+5*DPR};
    const clash=placed.some(p=>!(box.x+box.w<p.x||box.x>p.x+p.w||box.y+box.h<p.y||box.y>p.y+p.h));
    if(clash&&!sel&&!hov)return;
    placed.push(box);
    mx.lineWidth=3*DPR;mx.strokeStyle='rgba(8,12,20,.92)';mx.strokeText(c.id,lx,ly);
    mx.fillStyle=sel||hov?'#fff':'#c9d4e3';mx.fillText(c.id,lx,ly);
  });
  // Skip the innerHTML write when nothing changed — this runs every frame and
  // the string only moves while zoom eases or a control flips.
  const ctl=`<b>${live?'Feeds live · map '+PERIODS[tIdx]:PERIODS[tIdx]}</b> · ${sized.length} entities · ${fl.length} flows · sized by <b>${sizeBy==='mcap'?'market cap':'revenue'}</b> · zoom <b>${view.scale.toFixed(1)}×</b> · <span class="hon">${tIdx===ANCHOR?'flows modeled (E/I)':'flows = '+PERIODS[ANCHOR]+' figures ×'+TMUL[tIdx]}</span>`;
  if(ctl!==ctlPrev)ctlTopEl.innerHTML=ctlPrev=ctl;
}
const ctlTopEl=document.getElementById('ctlTop');let ctlPrev='';
function quad(a,c,b,t){const u=1-t;return{x:u*u*a.x+2*u*t*c.x+t*t*b.x,y:u*u*a.y+2*u*t*c.y+t*t*b.y};}
function arrow(f,t,col){const an=Math.atan2(t.y-f.y,t.x-f.x),sz=6*DPR;mx.fillStyle=col;mx.beginPath();mx.moveTo(t.x,t.y);mx.lineTo(t.x-sz*Math.cos(an-.4),t.y-sz*Math.sin(an-.4));mx.lineTo(t.x-sz*Math.cos(an+.4),t.y-sz*Math.sin(an+.4));mx.closePath();mx.fill();}
// Provenance marker: shape encodes the tier alongside color (color-blind-safe):
// R = circle, E = square, I = triangle.
function provDot(ctx,x,y,r,p){ctx.beginPath();
  if(p==='R')ctx.arc(x,y,r,0,6.28);
  else if(p==='E')ctx.rect(x-r*0.9,y-r*0.9,r*1.8,r*1.8);
  else{ctx.moveTo(x,y-r*1.15);ctx.lineTo(x+r*1.1,y+r*0.95);ctx.lineTo(x-r*1.1,y+r*0.95);ctx.closePath();}
  ctx.fill();ctx.stroke();}

/* ---- interaction (pointer events: mouse, touch, and pen) ---- */
let panning=false,last={x:0,y:0},moved=false,pinch0=null;
const ptrs=new Map(); // active pointers over the map: id -> CSS-px position
// Touch pointers get a larger hit target: small pins are ~8 CSS px, well under
// fingertip size, so floor the effective radius and widen the slop for touch.
function pick(px,py,touch){const dpr=DPR;px*=dpr;py*=dpr;let best=null,bd=1e9;for(const p of lastDrawn){const eff=touch?Math.max(p.r,12*dpr)+8*dpr:Math.max(p.r,5*dpr)+5*dpr;const d=Math.hypot(px-p.x,py-p.y);if(d<=eff&&d<bd){bd=d;best=p.c;}}return best;}
const hideTip=()=>{const tp=document.getElementById('tip');if(tp)tp.style.opacity=0;};
function zoomAbout(px,py,scale){ // rescale while keeping the (CSS-px) point fixed on screen
  const before=unproj(px*DPR,py*DPR);
  target.scale=view.scale=Math.max(0.8,Math.min(80,scale));
  const after=unproj(px*DPR,py*DPR);
  target.cx=view.cx+=before.lon-after.lon;target.cy=view.cy+=before.lat-after.lat;
}
map.addEventListener('pointerdown',e=>{
  map.setPointerCapture(e.pointerId);
  ptrs.set(e.pointerId,{x:e.offsetX,y:e.offsetY});
  if(ptrs.size===1){panning=true;moved=false;last={x:e.offsetX,y:e.offsetY};}
  else if(ptrs.size===2){panning=false;hideTip();const[a,b]=ptrs.values();pinch0={d:Math.hypot(a.x-b.x,a.y-b.y)||1,scale:view.scale};}
});
map.addEventListener('pointermove',e=>{
  const px=e.offsetX,py=e.offsetY;
  if(ptrs.has(e.pointerId))ptrs.set(e.pointerId,{x:px,y:py});
  if(pinch0&&ptrs.size===2){ // two-finger pinch: zoom about the finger midpoint
    const[a,b]=ptrs.values();
    zoomAbout((a.x+b.x)/2,(a.y+b.y)/2,pinch0.scale*(Math.hypot(a.x-b.x,a.y-b.y)/pinch0.d));
    moved=true;return;
  }
  // Click-slop: 2px cancelled taps/clicks constantly at high zoom, where pins
  // are small and a little hand jitter is normal — especially on touch.
  if(panning){const dx=px-last.x,dy=py-last.y;if(Math.abs(dx)+Math.abs(dy)>(e.pointerType==='mouse'?5:10))moved=true;const s=pxPerDeg()/DPR;target.cx-=dx/s;target.cy+=dy/(s*0.95);view.cx=target.cx;view.cy=target.cy;last={x:px,y:py};hideTip();return;}
  if(e.pointerType!=='mouse')return; // hover/tooltip is a mouse-only affordance
  const c=pick(px,py);hover=c;const tip=document.getElementById('tip');if(!tip)return;
  if(c){const isGov=c.mcap===0,np=nProv(c);tip.innerHTML=`<div class="t">${esc(c.name)}</div><div class="s">${SECNAME[c.sec]} · HQ ${esc(c.country)}</div><div class="s">${isGov?(CB.has(c.id)?'Balance sheet ~':'Annual flows ~')+fmt(revAt(c)):'Cap '+fmt(mcapOf(c))+' · Rev '+fmt(revAt(c))}</div><div class="pv"><i style="background:${PCOL[np]}"></i>${PNAME[np]} ${isGov?'(modeled)':(hasFact(c)?'revenue (SEC filing)':'revenue')}</div>`;tip.style.left=Math.min(px+16,map.clientWidth-248)+'px';tip.style.top=Math.min(py+16,map.clientHeight-100)+'px';tip.style.opacity=1;map.style.cursor='pointer';}
  else{tip.style.opacity=0;map.style.cursor='grab';}});
function endPointer(e){
  if(!ptrs.delete(e.pointerId))return;
  if(ptrs.size===1){pinch0=null;const[a]=ptrs.values();panning=true;moved=true;last={x:a.x,y:a.y};} // pinch ended: remaining finger keeps panning
  else if(ptrs.size===0){
    if(panning&&!moved&&e.type==='pointerup'){const c=pick(e.offsetX,e.offsetY,e.pointerType!=='mouse');if(c)selectNode(c.id);else if(selected)clearSelection();}
    panning=false;pinch0=null;
    if(e.pointerType!=='mouse')hideTip(); // touch never gets a pointerleave to clear it
  }
}
map.addEventListener('pointerup',endPointer);
map.addEventListener('pointercancel',endPointer);
map.addEventListener('pointerleave',e=>{if(!panning&&e.pointerType==='mouse'){hover=null;hideTip();}});
// Wheel zoom, normalized across devices: trackpads fire many small pixel-mode
// deltas while mouse wheels fire few large line-mode ones — a fixed per-event
// multiplier made trackpads zoom explosively. Scale exponentially by the
// actual normalized delta instead (~15% per 100px wheel notch), keeping the
// old feel for a mouse wheel while taming high-frequency trackpad streams.
map.addEventListener('wheel',e=>{e.preventDefault();
  const px=e.deltaMode===1?e.deltaY*16:e.deltaMode===2?e.deltaY*100:e.deltaY;
  zoomAbout(e.offsetX,e.offsetY,view.scale*Math.exp(-px*0.0015));
},{passive:false});
// Keep the double-clicked point fixed on screen while doubling the zoom
// (centering on the point instead made the view jump mid-ease).
map.addEventListener('dblclick',e=>{zoomAbout(e.offsetX,e.offsetY,view.scale*2);});
// Keyboard map control (the canvas is tabbable): arrows pan, +/- zoom, 0 fits.
map.addEventListener('keydown',e=>{
  const panDeg=60*DPR/pxPerDeg(); // ~60 CSS px per keypress at the current zoom
  if(e.key==='ArrowLeft')target.cx-=panDeg;
  else if(e.key==='ArrowRight')target.cx+=panDeg;
  else if(e.key==='ArrowUp')target.cy+=panDeg;
  else if(e.key==='ArrowDown')target.cy-=panDeg;
  else if(e.key==='+'||e.key==='=')target.scale=Math.min(80,target.scale*1.6);
  else if(e.key==='-'||e.key==='_')target.scale=Math.max(0.8,target.scale/1.6);
  else if(e.key==='0')fitView();
  else return;
  e.preventDefault();
});
// Single deselection path (empty-map click, Escape, fit): show the whole
// flow network again and reset the inspector.
function clearSelection(){selected=null;hover=null;renderInspectorEmpty();syncHash(true);}
function fitView(){target={cx:10,cy:25,scale:1};clearSelection();}
document.getElementById('zin').onclick=()=>target.scale=Math.min(80,target.scale*1.6);
document.getElementById('zout').onclick=()=>target.scale=Math.max(0.8,target.scale/1.6);
document.getElementById('zfit').onclick=fitView;

/* ---- inspector ---- */
// fly=false refreshes the inspector in place (filter/scrub changes) without
// re-aiming the camera at the node.
let sbOpen=false; // state-breakdown "show all" toggle; collapses again on node change
function selectNode(id,fly=true){const n=byId[id];if(!n)return;if(selected!==id)sbOpen=false;selected=id;const m=TMUL[tIdx],np=nProv(n),fx=FACTS[id];
  if(fly){target.cx=n.lng;target.cy=n.lat;if(target.scale<2)target.scale=2.2;}
  const outs=FL.filter(e=>e.f===id&&layerOn[e.p]&&nodeVis(byId[e.t])).map(e=>({...e,vv:e.v*m}));
  const ins=FL.filter(e=>e.t===id&&layerOn[e.p]&&nodeVis(byId[e.f])).map(e=>({...e,vv:e.v*m}));
  const sO=outs.reduce((a,b)=>a+b.vv,0),sI=ins.reduce((a,b)=>a+b.vv,0);
  const outsS=[...outs].sort((a,b)=>b.vv-a.vv),insS=[...ins].sort((a,b)=>b.vv-a.vv);
  const net=sI-sO,conc=outsS.length?Math.round(outsS[0].vv/sO*100):0;
  // YoY delta from the real SEC series (only when both years are reported)
  const cur=fx&&fx.revT[PERIODS[tIdx]],prv=fx&&fx.revT[String(+PERIODS[tIdx]-1)];
  const yoy=(cur!=null&&prv>0)?Math.round((cur-prv)/prv*100):null;
  const mv=Math.max(1,...outs.map(x=>x.vv),...ins.map(x=>x.vv));
  // Geographic breakdown for household macro nodes (US states, EU countries,
  // China provinces, Japan / rest-of-world regions): an allocation of the
  // node's household total, so each row scales with the scrubbed year exactly
  // like the headline flows number. Long lists collapse to a top-10 toggle.
  // res-flagged residual rows ("Other …") always sort last, whatever their share.
  const sb=STATE_SHARES[id],sbRows=sb?[...sb.rows].sort((a,b)=>(a.res?1:0)-(b.res?1:0)||b.sh-a.sh):[];
  const sbMax=sbRows.length?Math.max(...sbRows.map(r=>r.sh)):1;
  const stateRow=r=>`<div class="flow" role="button" tabindex="0" data-st="${r.a}" aria-label="${esc(r.n)}, ${fmt(r.sh*revAt(n))}, ${(r.sh*100).toFixed(1)}% of total household outflows"><div class="r1"><div class="who"><span class="ar">◆</span><span>${esc(r.n)}</span><span class="tag ${sb.p}">${PNAME[sb.p][0]}</span></div><div class="amt">${fmt(r.sh*revAt(n))}</div></div><div class="bar"><i style="width:${Math.min(100,r.sh/sbMax*100)}%;background:${PCOL[sb.p]}"></i></div><div class="meth">${(r.sh*100).toFixed(1)}% of total household outflows</div></div>`;
  const stateSec=sb?`<div class="flowsec" style="border-top:1px solid var(--line)"><div class="lbl">Breakdown by ${sb.t} <span>${sbRows.length}</span></div><div style="color:var(--mut);font-size:11px;margin:-2px 0 8px">Estimated allocation of the household total by ${sb.t}-level consumption shares. Select a ${sb.t} for methodology.</div>${(sbOpen||sbRows.length<=10?sbRows:sbRows.slice(0,10)).map(stateRow).join('')}${sbRows.length>10?`<button class="ddbtn" id="sbToggle" style="margin:10px 0 4px;width:100%">${sbOpen?'Show top 10 only':'Show all '+sbRows.length+' '+sb.tp+' →'}</button>`:''}</div>`:'';
  const flowRow=(e,dir)=>{const o=dir==='out'?e.t:e.f,oc=byId[o],fp=fProv(e),kd=kindOf(e);return `<div class="flow" role="button" tabindex="0" data-e="${e.f}|${e.t}" aria-label="${dir==='out'?'Outflow to':'Inflow from'} ${esc(oc.name)}, ${fmt(e.vv)}, ${PNAME[fp]}"><div class="r1"><div class="who"><span class="ar">${dir==='out'?'→':'←'}</span><span style="width:9px;height:9px;border-radius:50%;background:${SEC[oc.sec]};display:inline-block"></span><span class="cplink" data-go="${o}" title="Open ${esc(oc.name)}">${esc(oc.name)}</span><span class="tag ${fp}">${PNAME[fp][0]}</span></div><div class="amt">${fmt(e.vv)}</div></div><div class="bar"><i style="width:${Math.min(100,e.vv/mv*100)}%;background:${PCOL[fp]}"></i></div><div class="meth">${KIND_LABEL[kd]} · source quality ${(e.c*100|0)}%</div></div>`;};
  const html=`
   <div class="ihead"><div class="tk">${n.id}</div><div class="nm">${esc(n.name)}</div>
     <div class="meta"><span class="pill"><span class="d" style="background:${SEC[n.sec]}"></span>${SECNAME[n.sec]}</span><span class="pill" title="Pin marks the headquarters location (manually curated)">HQ · ${n.country}</span></div></div>
   <div class="stats">
     <div class="stat"><div class="k">${n.mcap===0?(CB.has(n.id)?'BALANCE SHEET (STOCK)':'ANNUAL FLOWS'):'MARKET CAP'}</div><div class="v">${n.mcap===0?fmt(revAt(n)):fmt(mcapOf(n))}<span class="tag ${n.mcap===0?np:'E'}">${n.mcap===0?PNAME[np][0]:'E'}</span></div>${n.mcap!==0?`<div class="k" style="margin-top:2px">${MCAPS[n.id]&&MCAP_ASOF?`as of ${MCAP_ASOF} · price × shares outstanding`:'point-in-time, not historical'}</div>`:''}</div>
     <div class="stat"><div class="k">REVENUE · ${PERIODS[tIdx]}</div><div class="v">${fmt(revAt(n))}<span class="tag ${np}">${PNAME[np][0]}</span></div></div>
     <div class="stat"><div class="k">OUTFLOWS</div><div class="v" style="color:var(--accent)">${fmt(sO)}</div></div>
     <div class="stat"><div class="k">INFLOWS</div><div class="v" style="color:var(--live)">${fmt(sI)}</div></div>
     <div class="stat"><div class="k">NET FLOW</div><div class="v" style="color:${net>=0?'var(--live)':'var(--inferred)'}">${net>=0?'+':'−'}${fmt(Math.abs(net))}</div></div>
     <div class="stat"><div class="k">TOP OUTFLOW SHARE</div><div class="v">${outsS.length?conc+'%':'—'}</div>${outsS.length?`<div class="k" style="margin-top:2px">to ${byId[outsS[0].t].name}</div>`:''}</div>
   </div>
   ${fx?`<div class="nsw"><div class="k">SEC-REPORTED REVENUE SERIES${yoy!=null?` · <span class="${yoy>=0?'up':'down'}">${yoy>=0?'+':''}${yoy}% YoY</span>`:''}</div><canvas id="nspark" aria-label="Reported revenue ${PERIODS[0]}–${PERIODS[PERIODS.length-1]}"></canvas><div class="yrs"><span>${PERIODS[0]}</span><span>${PERIODS[PERIODS.length-1]}</span></div></div>`:''}
   <button class="ddbtn" id="openDD">View relationship graph →</button>
   ${hasFact(n)?`<div class="verdict ok">✓ Revenue is the reported figure from SEC XBRL filings (10-K/20-F, through ${fx.asOf}) — scrubbing years shows the real series, not an estimate. <a href="${fx.url}" target="_blank" rel="noopener noreferrer">Verify at SEC ↗</a></div>`:fx?`<div class="verdict warn">⚠ No SEC filing figure for ${PERIODS[tIdx]} — showing a modeled estimate for this year. <a href="${fx.url}" target="_blank" rel="noopener noreferrer">Verify other years at SEC ↗</a></div>`:np==='R'?`<div class="verdict ok">✓ Revenue anchored to a primary filing. Market cap is point-in-time (tagged Estimated — it moves every trading day).</div>`:`<div class="verdict warn">⚠ Revenue carries a ${PNAME[np]} tag — modeled or not yet verified against a filing. Treat as directional.</div>`}
   ${stateSec}
   <div class="flowsec"><div class="lbl">Outflows <span>${outs.length}</span></div>${outsS.length?outsS.map(e=>flowRow(e,'out')).join(''):'<div style="color:var(--mut);font-size:12px;padding:6px 0">No seeded outflows. In production these derive from supplier disclosures + input-output tables.</div>'}</div>
   <div class="flowsec" style="border-top:1px solid var(--line)"><div class="lbl">Inflows <span>${ins.length}</span></div>${insS.length?insS.map(e=>flowRow(e,'in')).join(''):'<div style="color:var(--mut);font-size:12px;padding:6px 0">No seeded inflows in current view.</div>'}</div>
   <div class="mblock" id="methblock"><div class="lbl">Methodology</div><div style="color:var(--mut);font-size:12px">Select a flow above to see how its figure was derived.</div></div>`;
  const el=document.getElementById('inspector');el.innerHTML=html;
  el.querySelectorAll('.flow[data-e]').forEach(r=>{const go=()=>{const[f,t]=r.dataset.e.split('|');showMethod(FL.find(e=>e.f===f&&e.t===t));};r.onclick=go;r.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go();}};});
  // state breakdown rows open methodology; the toggle re-renders in place
  el.querySelectorAll('.flow[data-st]').forEach(r=>{const go=()=>showStateMethod(n,sb,sb.rows.find(x=>x.a===r.dataset.st));r.onclick=go;r.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go();}};});
  const sbT=document.getElementById('sbToggle');if(sbT)sbT.onclick=()=>{sbOpen=!sbOpen;selectNode(id,false);};
  // counterparty names navigate to that node (flow row body still opens methodology)
  el.querySelectorAll('.cplink').forEach(s=>{s.onclick=e=>{e.stopPropagation();selectNode(s.dataset.go);};});
  document.getElementById('openDD').onclick=()=>openDrill(id);
  // sparkline of the real reported series, with a marker on the scrubbed year
  const cv=document.getElementById('nspark');
  const pts=fx?PERIODS.map((p,i)=>({i,v:fx.revT[p]})).filter(d=>d.v!=null):[];
  if(cv&&pts.length){const g=cv.getContext('2d');const w=cv.clientWidth||300,h=46;
    cv.width=Math.round(w*DPR);cv.height=Math.round(h*DPR);g.setTransform(DPR,0,0,DPR,0,0);
    const lo=Math.min(...pts.map(d=>d.v)),hi=Math.max(...pts.map(d=>d.v));
    const X=i=>10+i/(PERIODS.length-1)*(w-20),Y=v=>h-8-((v-lo)/((hi-lo)||1))*(h-18);
    g.strokeStyle=PCOL.R;g.lineWidth=1.8;g.beginPath();pts.forEach((d,k)=>k?g.lineTo(X(d.i),Y(d.v)):g.moveTo(X(d.i),Y(d.v)));g.stroke();
    g.fillStyle=PCOL.R;pts.forEach(d=>{g.beginPath();g.arc(X(d.i),Y(d.v),2,0,6.28);g.fill();});
    if(cur!=null){g.fillStyle='#fff';g.beginPath();g.arc(X(tIdx),Y(cur),3.2,0,6.28);g.fill();
      g.font='600 10px Inter,sans-serif';g.textAlign='center';g.fillStyle='#e8eef7';
      g.fillText(fmt(cur),Math.min(w-26,Math.max(26,X(tIdx))),Math.max(10,Y(cur)-8));}
  }
  syncHash(fly);
}
function renderInspectorEmpty(){const el=document.getElementById('inspector');el.innerHTML='<div class="ins-empty"><div class="big">◎</div>Select any node on the map to inspect its scale, capital flows, counterparties, and the provenance behind every figure.<div class="note" style="margin-top:12px">Illustrative dataset — revenue is SEC-verified where tagged R. <a href="#about" id="abLink" style="color:var(--accent)">About the data</a></div></div>';const l=document.getElementById('abLink');if(l)l.onclick=e=>{e.preventDefault();openAbout();};}
function showMethod(e){if(!e)return;const b=document.getElementById('methblock');if(!b)return;
  b.innerHTML=`<div class="lbl">Methodology · ${e.f} → ${e.t}</div>
   <div class="mb-row"><span class="k">Value (${PERIODS[tIdx]})</span><span class="v">${fmt(e.v*TMUL[tIdx])}</span></div>
   <div class="mb-row"><span class="k">Provenance</span><span class="v"><span class="tag ${fProv(e)}">${PNAME[fProv(e)]}</span></span></div>
   <div class="mb-row"><span class="k">Source quality</span><span class="v">${(e.c*100|0)}%</span></div>
   <div class="track" style="margin-top:6px"><i style="width:${e.c*100}%;background:${PCOL[fProv(e)]}"></i></div>
   ${tIdx!==ANCHOR?`<div class="prov-txt">⚠ <b>Scaled figure.</b> This is the ${PERIODS[ANCHOR]} value ×${TMUL[tIdx]} (global year multiplier), not a reported ${PERIODS[tIdx]} figure${e.p==='R'?' — the Reported tag applies to the anchor year only':''}.</div>`:''}
   <div class="prov-txt"><b>Method.</b> ${e.m}</div><div class="prov-txt"><b>Source.</b> ${e.s}</div>`;
  b.scrollIntoView({behavior:'smooth',block:'nearest'});
}
// Methodology panel for a regional-breakdown row: the figure is an allocation
// of the node's household total, so it shares one method/source for all rows.
function showStateMethod(n,sb,r){if(!r)return;const b=document.getElementById('methblock');if(!b)return;
  b.innerHTML=`<div class="lbl">Methodology · ${n.id} · ${r.n}</div>
   <div class="mb-row"><span class="k">Est. outflows (${PERIODS[tIdx]})</span><span class="v">${fmt(r.sh*revAt(n))}</span></div>
   <div class="mb-row"><span class="k">Share of household total</span><span class="v">${(r.sh*100).toFixed(1)}%</span></div>
   <div class="mb-row"><span class="k">Provenance</span><span class="v"><span class="tag ${sb.p}">${PNAME[sb.p]}</span></span></div>
   ${tIdx!==ANCHOR?`<div class="prov-txt">⚠ <b>Scaled figure.</b> The household total is the ${PERIODS[ANCHOR]} figure ×${TMUL[tIdx]} (global year multiplier); the ${sb.t} share is held constant across years.</div>`:''}
   <div class="prov-txt"><b>Method.</b> ${sb.m}</div><div class="prov-txt"><b>Source.</b> ${sb.s}</div>`;
  b.scrollIntoView({behavior:'smooth',block:'nearest'});
}

/* ---- drill modal (force graph) ---- */
const modal=document.getElementById('modal'),dd=document.getElementById('dd'),dx=dd.getContext('2d');
let ddN=[],ddDrag=null,ddRAF=null,ddC=null,ddPrevFocus=null;
document.getElementById('ddClose').onclick=closeDrill;
modal.addEventListener('mousedown',e=>{if(e.target===modal)closeDrill();});
// Keep keyboard focus inside the dialog while it's open (only the close button is
// focusable, so Tab parks there rather than leaking into the page behind).
modal.addEventListener('keydown',e=>{if(e.key==='Tab'&&modal.classList.contains('show')){e.preventDefault();document.getElementById('ddClose').focus();}});
function openDrill(id){ddPrevFocus=document.activeElement;ddC=id;const eg=FL.filter(e=>(e.f===id||e.t===id)&&layerOn[e.p]);const ids=new Set([id]);eg.forEach(e=>{ids.add(e.f);ids.add(e.t);});ddN=[...ids].map((nid,i)=>{const an=i/ids.size*6.28;return{id:nid,x:nid===id?0:Math.cos(an)*170,y:nid===id?0:Math.sin(an)*170,vx:0,vy:0};});document.getElementById('ddTitle').textContent='Relationships · '+byId[id].name;document.getElementById('ddFoot').innerHTML=`${eg.length} seeded flows. Line style = provenance (solid reported · dashed estimated · dotted inferred). Drag to rearrange. Production resolves the full counterparty set from filings and input-output tables.`;modal.classList.add('show');document.getElementById('ddClose').focus();cancelAnimationFrame(ddRAF);ddLoop();}
function closeDrill(){modal.classList.remove('show');cancelAnimationFrame(ddRAF);if(ddPrevFocus&&ddPrevFocus.focus){try{ddPrevFocus.focus();}catch{/* element gone */}}}
function ddLoop(){
  // Resize the backing store only when needed (reassigning width every frame
  // forces a clear + GPU realloc); the explicit clearRect below wipes the frame.
  const cw=Math.round(dd.clientWidth*DPR),ch=Math.round(dd.clientHeight*DPR);
  if(dd.width!==cw||dd.height!==ch){dd.width=cw;dd.height=ch;}
  dx.setTransform(DPR,0,0,DPR,0,0);const W=dd.clientWidth,H=dd.clientHeight,cx=W/2,cy=H/2;const m=Object.fromEntries(ddN.map(n=>[n.id,n]));const eg=FL.filter(e=>m[e.f]&&m[e.t]&&layerOn[e.p]);
  for(let i=0;i<ddN.length;i++)for(let j=i+1;j<ddN.length;j++){const a=ddN[i],b=ddN[j];let ax=a.x-b.x,ay=a.y-b.y,d2=ax*ax+ay*ay||1,f=30000/d2,d=Math.sqrt(d2);a.vx+=ax/d*f;a.vy+=ay/d*f;b.vx-=ax/d*f;b.vy-=ay/d*f;}
  eg.forEach(e=>{const a=m[e.f],b=m[e.t],ax=b.x-a.x,ay=b.y-a.y,d=Math.hypot(ax,ay)||1,f=(d-160)*0.01;a.vx+=ax/d*f;a.vy+=ay/d*f;b.vx-=ax/d*f;b.vy-=ay/d*f;});
  ddN.forEach(n=>{if(n.id===ddC){n.x=0;n.y=0;return;}n.vx+=-n.x*0.01;n.vy+=-n.y*0.01;if(n!==ddDrag){n.x+=n.vx*0.5;n.y+=n.vy*0.5;}n.vx*=0.85;n.vy*=0.85;});
  dx.clearRect(0,0,W,H);
  eg.forEach(e=>{const a=m[e.f],b=m[e.t],fp=fProv(e);dx.strokeStyle=PCOL[fp];dx.globalAlpha=0.85;dx.setLineDash(fp==='R'?[]:(fp==='E'?[6,4]:[2,5]));dx.lineWidth=Math.max(1,Math.log(e.v+1)*0.7);dx.beginPath();dx.moveTo(cx+a.x,cy+a.y);dx.lineTo(cx+b.x,cy+b.y);dx.stroke();dx.setLineDash([]);const t=pulse%1,px=a.x+(b.x-a.x)*t,py=a.y+(b.y-a.y)*t;dx.fillStyle=PCOL[fp];dx.globalAlpha=1;dx.beginPath();dx.arc(cx+px,cy+py,2.6,0,6.28);dx.fill();dx.fillStyle='#c9d4e3';dx.font='10px Inter,sans-serif';dx.textAlign='center';dx.fillText(fmt(e.v*TMUL[tIdx]),cx+(a.x+b.x)/2,cy+(a.y+b.y)/2-4);});
  dx.globalAlpha=1;
  ddN.forEach(n=>{const c=byId[n.id],r=n.id===ddC?28:19;dx.beginPath();dx.arc(cx+n.x,cy+n.y,r,0,6.28);dx.fillStyle=SEC[c.sec];dx.globalAlpha=n.id===ddC?1:0.88;dx.shadowBlur=n.id===ddC?16:6;dx.shadowColor=SEC[c.sec];dx.fill();dx.shadowBlur=0;dx.globalAlpha=1;dx.lineWidth=n.id===ddC?3:1.5;dx.strokeStyle='#fff';dx.stroke();const dnp=nProv(c);dx.fillStyle=PCOL[dnp];dx.strokeStyle='#101725';dx.lineWidth=1.4;provDot(dx,cx+n.x+r*0.7,cy+n.y-r*0.7,3.4,dnp);dx.fillStyle='#fff';dx.font='600 11px Inter,sans-serif';dx.textAlign='center';dx.fillText(n.id,cx+n.x,cy+n.y+r+14);});
  ddRAF=requestAnimationFrame(ddLoop);}
dd.addEventListener('pointerdown',e=>{dd.setPointerCapture(e.pointerId);const px=e.offsetX-dd.clientWidth/2,py=e.offsetY-dd.clientHeight/2;ddDrag=ddN.find(n=>Math.hypot(px-n.x,py-n.y)<(n.id===ddC?33:24))||null;});
dd.addEventListener('pointermove',e=>{if(ddDrag){ddDrag.x=e.offsetX-dd.clientWidth/2;ddDrag.y=e.offsetY-dd.clientHeight/2;ddDrag.vx=ddDrag.vy=0;}});
dd.addEventListener('pointerup',()=>ddDrag=null);
dd.addEventListener('pointercancel',()=>ddDrag=null);

/* ---- panels ---- */
function buildSectors(){const ct={};C.forEach(c=>ct[c.sec]=(ct[c.sec]||0)+1);document.getElementById('sectors').innerHTML=Object.keys(SEC).map(s=>`<button class="chip ${secOn[s]?'on':''}" data-s="${s}" style="${secOn[s]?'background:'+SEC[s]+'1a;border-color:'+SEC[s]+'66':''}"><span class="l"><span class="d" style="background:${SEC[s]}"></span>${SECNAME[s]}</span><span class="ct">${ct[s]}</span></button>`).join('');document.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>{secOn[b.dataset.s]=!secOn[b.dataset.s];buildSectors();refreshStats();if(selected)selectNode(selected,false);syncHash(false);});}
function buildLayers(){const L={R:'Filing-anchored revenue & disclosures',E:'Modeled from disclosure + I-O; point-in-time caps',I:'Third-party or allocation heuristics'};document.getElementById('layers').innerHTML=Object.keys(L).map(k=>`<div class="leg ${layerOn[k]?'':'off'}" data-l="${k}" role="switch" tabindex="0" aria-checked="${layerOn[k]?'true':'false'}" aria-label="${PNAME[k]} layer"><span class="ln" style="border-color:${PCOL[k]};border-top-style:${k==='R'?'solid':k==='E'?'dashed':'dotted'}"></span><div><div class="ttl" style="color:${PCOL[k]}">${PNAME[k]}</div><div class="sub">${L[k]}</div></div></div>`).join('');document.querySelectorAll('[data-l]').forEach(el=>{const go=()=>{layerOn[el.dataset.l]=!layerOn[el.dataset.l];buildLayers();refreshStats();if(selected)selectNode(selected,false);syncHash(false);};el.onclick=go;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go();}};});}
function refreshStats(){const sc=visC(),fl=visF();map.setAttribute('aria-label','Capital-flow world map — '+sc.length+' entities and '+fl.length+' flows shown for period '+(live?'live (simulated)':PERIODS[tIdx])+'. When focused: arrow keys pan, plus and minus zoom, zero resets. Use the search box and side panels to explore entity details and provenance.');document.getElementById('hCap').textContent=fmt(sc.reduce((a,c)=>a+mcapOf(c),0));document.getElementById('hF').textContent=fl.length;document.getElementById('hN').textContent=sc.length;const mix={R:0,E:0,I:0};fl.forEach(e=>mix[fProv(e)]+=e.vv);const tot=mix.R+mix.E+mix.I||1;document.getElementById('provmix').innerHTML=['R','E','I'].map(k=>`<div class="mixrow"><div class="h"><b style="color:${PCOL[k]}">${PNAME[k]}</b><span>${(mix[k]/tot*100).toFixed(0)}%</span></div><div class="track"><i style="width:${mix[k]/tot*100}%;background:${PCOL[k]}"></i></div></div>`).join('')+`<div class="note">Share of visible flow volume by source quality. Toggle layers to see how much rests on modeling vs. reported figures.</div>`;}

/* ---- search (ranked: exact ticker ≫ ticker prefix ≫ name ≫ country) ---- */
const srch=document.getElementById('srch'),reslist=document.getElementById('reslist');
let srchIdx=-1;
function searchScore(c,q){
  const id=c.id.toLowerCase(),nm=c.name.toLowerCase();
  const tie=Math.min(9,((mcapOf(c)||c.rev)||0)/500); // big entities float on ties
  if(id===q)return 100+tie;
  if(id.startsWith(q))return 80+tie;
  if(nm.startsWith(q))return 60+tie;
  if(nm.includes(q))return 40+tie;
  if(c.country.toLowerCase().includes(q))return 20+tie;
  return -1;
}
srch.oninput=()=>{srchIdx=-1;const q=srch.value.toLowerCase().trim();if(!q){reslist.innerHTML='';return;}
  const h=C.map(c=>[searchScore(c,q),c]).filter(([s])=>s>=0).sort((a,b)=>b[0]-a[0]).slice(0,24).map(([,c])=>c);
  reslist.innerHTML=h.map(c=>`<div class="resrow" role="option" tabindex="0" data-id="${c.id}" id="sr-${c.id}"><span class="dot" style="background:${SEC[c.sec]}"></span><span class="nm">${esc(c.name)}</span><span class="cty">${esc(c.country)}</span></div>`).join('')||'<div class="note" style="padding:8px">No matches.</div>';
  reslist.querySelectorAll('[data-id]').forEach(r=>{const go=()=>{selectNode(r.dataset.id);srch.value='';reslist.innerHTML='';srchIdx=-1;};r.onclick=go;r.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go();}};});};
// Arrow keys walk the results from the input; Enter selects (default: top hit).
srch.onkeydown=e=>{
  const rows=[...reslist.querySelectorAll('[data-id]')];
  if(e.key==='Escape'){e.stopPropagation();srch.value='';reslist.innerHTML='';srchIdx=-1;return;}
  if(!rows.length)return;
  if(e.key==='ArrowDown'){e.preventDefault();srchIdx=Math.min(rows.length-1,srchIdx+1);}
  else if(e.key==='ArrowUp'){e.preventDefault();srchIdx=Math.max(0,srchIdx-1);}
  else if(e.key==='Enter'){e.preventDefault();(rows[Math.max(0,srchIdx)]||rows[0]).click();return;}
  else return;
  rows.forEach((r,i)=>r.classList.toggle('active',i===srchIdx));
  // announce the highlighted result to assistive tech without moving DOM focus
  srch.setAttribute('aria-activedescendant',rows[srchIdx]?rows[srchIdx].id:'');
  if(rows[srchIdx])rows[srchIdx].scrollIntoView({block:'nearest'});
};

/* ---- size toggle / time / live ---- */
document.querySelectorAll('#sizeBy button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#sizeBy button').forEach(x=>x.classList.remove('on'));b.classList.add('on');sizeBy=b.dataset.by;syncHash(false);});
const scrub=document.getElementById('scrub');scrub.oninput=()=>{tIdx=+scrub.value;document.getElementById('period').textContent=PERIODS[tIdx];refreshStats();if(selected)selectNode(selected,false);syncHash(false);};
let playIv=null;
document.getElementById('play').onclick=function(){playing=!playing;this.textContent=playing?'⏸':'▶';this.setAttribute('aria-label',playing?'Pause timeline':'Play timeline');clearInterval(playIv);playIv=null;if(playing){playIv=setInterval(()=>{tIdx=(tIdx+1)%PERIODS.length;scrub.value=tIdx;scrub.oninput();},1100);}};
const feeds=[{k:'WTI Crude',v:72.4,u:''},{k:'Brent',v:76.1,u:''},{k:'USD/JPY',v:151.2,u:''},{k:'EUR/USD',v:1.083,u:''},{k:'10Y UST',v:4.21,u:'%'},{k:'Gold',v:2032,u:''},{k:'Bitcoin',v:97000,u:''}];
const sd=Array.from({length:90},()=>50);
// Real quotes where a keyless, CORS-open API exists: Frankfurter (ECB FX) and
// CoinGecko (BTC, PAXG as a gold proxy). Rows the APIs cover are marked "live";
// the rest stay an honest simulation marked "sim". Fetches run only while the
// Live toggle is on, and any failure (offline, rate limit, file://) silently
// leaves the row simulating — no console noise, no broken panel.
let liveIv=null;
async function fetchFeeds(){
  if(!live)return;
  // Only accept finite positive numbers — a malformed API response must not
  // poison the feeds array (values get .toFixed()'d straight into the DOM).
  const set=(k,val)=>{const f=feeds.find(x=>x.k===k);if(f&&Number.isFinite(val)&&val>0){f.dir=val>=f.v;f.v=val;f.real=true;}};
  // Each API fails independently — a CoinGecko rate-limit must not take the
  // ECB FX rows down with it (and vice versa). Failed rows keep simulating.
  await Promise.all([
    fetch('https://api.frankfurter.dev/v1/latest?base=USD&symbols=JPY,EUR').then(r=>r.json())
      .then(fx=>{if(fx&&fx.rates){set('USD/JPY',fx.rates.JPY);set('EUR/USD',1/fx.rates.EUR);}}).catch(()=>{}),
    fetch('https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,pax-gold&vs_currencies=usd').then(r=>r.json())
      .then(cg=>{if(cg){if(cg['pax-gold'])set('Gold',cg['pax-gold'].usd);if(cg.bitcoin)set('Bitcoin',cg.bitcoin.usd);}}).catch(()=>{})
  ]);
  tick();
}
function startLiveFetch(){clearInterval(liveIv);liveIv=null;if(live){fetchFeeds();liveIv=setInterval(fetchFeeds,60000);}}
// Direction coloring only applies while live — before the sim runs there's no
// tick-to-tick move, so values stay neutral instead of all reading as "down".
function tick(){if(live)feeds.forEach(f=>{if(f.real)return;const d=(Math.random()-0.5)*f.v*0.004;f.v=Math.max(.001,f.v+d);f.dir=d>=0;});const anyReal=feeds.some(f=>f.real);const tg=document.getElementById('feedTag');if(tg)tg.textContent=anyReal?'MIXED':'SIM';document.getElementById('feeds').innerHTML=feeds.map(f=>`<div class="feed"><span class="k">${f.k}</span><span class="v ${live?(f.dir?'up':'down'):''}">${f.v>100?f.v.toFixed(1):f.v.toFixed(3)}${f.u} ${live?(f.dir?'▲':'▼'):''}${live?`<i class="fsrc">${f.real?'live':'sim'}</i>`:''}</span></div>`).join('');if(live){sd.push(sd[sd.length-1]+(Math.random()-.48)*6);sd.shift();}drawSpark();}
const sc=document.getElementById('spark'),sx=sc.getContext('2d');
function drawSpark(){const cw=Math.round(sc.clientWidth*DPR),ch=Math.round(38*DPR);if(sc.width!==cw||sc.height!==ch){sc.width=cw;sc.height=ch;}sx.setTransform(DPR,0,0,DPR,0,0);const w=sc.clientWidth,h=38,mn=Math.min(...sd),mv=Math.max(...sd);sx.clearRect(0,0,w,h);sx.beginPath();sd.forEach((v,i)=>{const x=i/sd.length*w,y=h-((v-mn)/((mv-mn)||1))*(h-6)-3;i?sx.lineTo(x,y):sx.moveTo(x,y);});sx.strokeStyle=live?'#2dd4e8':'#5b8cff';sx.lineWidth=1.8;sx.stroke();}
document.getElementById('liveBtn').onclick=function(){live=!live;this.classList.toggle('on',live);this.setAttribute('aria-pressed',live?'true':'false');document.getElementById('liveDot').classList.toggle('on',live);document.getElementById('period').textContent=live?'LIVE':PERIODS[tIdx];if(!live)feeds.forEach(f=>delete f.real);startLiveFetch();};
const clockFn=()=>document.getElementById('clock').textContent=new Date().toLocaleTimeString('en-GB');
let tickIv=setInterval(tick,900),clockIv=setInterval(clockFn,1000);
// Pause the always-on timers while the tab is hidden — no point burning CPU/battery
// on the simulated feed + clock for a tab nobody's looking at. (The RAF render loop
// is already suspended by the browser when backgrounded.)
document.addEventListener('visibilitychange',()=>{
  clearInterval(tickIv);clearInterval(clockIv);clearInterval(liveIv);liveIv=null;
  if(!document.hidden){tickIv=setInterval(tick,900);clockIv=setInterval(clockFn,1000);clockFn();startLiveFetch();}
});
/* ---- about modal ---- */
const aboutModal=document.getElementById('aboutModal');
let abPrevFocus=null;
function openAbout(){abPrevFocus=document.activeElement;aboutModal.classList.add('show');document.getElementById('abClose').focus();}
function closeAbout(){aboutModal.classList.remove('show');if(abPrevFocus&&abPrevFocus.focus){try{abPrevFocus.focus();}catch{/* element gone */}}}
document.getElementById('aboutBtn').onclick=openAbout;
document.getElementById('abClose').onclick=closeAbout;
aboutModal.addEventListener('mousedown',e=>{if(e.target===aboutModal)closeAbout();});
// About modal has real content (links) — cycle Tab through its focusables
// instead of parking on the close button, so keyboard users can reach them.
aboutModal.addEventListener('keydown',e=>{
  if(e.key!=='Tab'||!aboutModal.classList.contains('show'))return;
  const f=[...aboutModal.querySelectorAll('button,a[href]')];
  if(!f.length)return;
  const first=f[0],last=f[f.length-1],cur=document.activeElement;
  if(e.shiftKey&&(cur===first||!f.includes(cur))){e.preventDefault();last.focus();}
  else if(!e.shiftKey&&(cur===last||!f.includes(cur))){e.preventDefault();first.focus();}
});

// Escape closes whichever overlay is open, otherwise clears the active view's
// selection — which selection that is depends on the tab you are looking at.
window.addEventListener('keydown',e=>{
  if(e.key!=='Escape')return;
  if(rentModal.classList.contains('show'))closeDossier();
  else if(aboutModal.classList.contains('show'))closeAbout();
  else if(modal.classList.contains('show'))closeDrill();
  else if(tab==='rents'){if(rSel){rSel=null;renderRentEmpty();buildRentList();;syncHash(true);}}
  else if(selected)clearSelection();
});

/* ---- scarcity board ----
   The second tab. Subject: scarcity rents — things whose price has diverged far
   above the cost of new supply because supply cannot respond. Same provenance
   machinery as the map (PCOL / PNAME / .tag), different question. */
const RCAT={compute:'#5b8cff',power:'#f5b042',materials:'#ed8f00',pharma:'#3fd68a',labor:'#f472b6',logistics:'#a78bfa',infra:'#2dd4e8',agri:'#1fb979',defense:'#ff6b7a',regulated:'#e2e8f0'};
const ABY=Object.fromEntries(ARCHIVE.map(a=>[a.id,a]));
// rMult / rentScore / rentProv / rentConf live in rents.js beside the data, so
// the unit tests score exactly what the board scores.
const rProv=rentProv;
// Prices here span $/GB to $M/tool, so significant digits scale with magnitude.
const PWORD={R:'published',E:'estimated',I:'modelled'};
const rnum=v=>v>=10000?Math.round(v).toLocaleString('en-US'):v>=100?v.toFixed(0):v>=10?v.toFixed(1):v.toFixed(2);
const rmo=m=>m>=24?(m/12).toFixed(m%12?1:0)+' yr':m+' mo';
const rpct=v=>(v*100).toFixed(0)+'%';

let tab='map',rSort='score',rDir=-1,rSel=null,rQ='',rScale='big';

/* Two boards, one machine. The industrial set asks how big the rent is; the
   micro set asks whether a person could actually go and take it. Everything
   that differs between them — the data, the enums, the score, the sort menu,
   the columns — hangs off this descriptor, so the list, filters, inspector and
   hash code below are written once. */
const BOARDS={
  big:{
    set:RENTS,cats:CATS,ccol:RCAT,bars:BARS,barwhy:BARWHY,asof:RENT_ASOF,
    score:rentScore,prov:rentProv,mult:rMult,
    // One definition per visible column, driving the header, the cell and the
    // sort together — a table whose header can disagree with its own ordering
    // is worse than no table.
    cols:[
      {k:'score',lab:'#',w:'34px',cls:'rk',ttl:'Overall score: 30% gap, 28% money, 20% persistence, 12% concentration, 10% margin',
       get:e=>rentScore(e),cell:(e,rank)=>String(rank[e.id])},
      {k:'name',lab:'Signal',w:'minmax(140px,1fr)',cls:'nm',txt:1,get:e=>e.pn,cell:e=>nameCell(e)},
      {k:'px',lab:'$',w:'82px',ttl:'What a buyer pays today',get:e=>e.px.v,cell:e=>esc(rPrice(e.px.v,e.u))},
      {k:'gap',lab:'Gap',w:'56px',ttl:'Price over the baseline it would cost if supply could respond',
       get:e=>rMult(e),cell:e=>rMult(e).toFixed(1)+'×'},
      {k:'pool',lab:'Excess / yr',w:'84px',ttl:'Annual spend above the baseline, across the whole market',
       get:e=>e.pool.v,cell:e=>esc(fmt(e.pool.v))},
      {k:'vol',lab:'Volume',w:'84px',ttl:'Units a year implied by the excess and the price gap',
       get:e=>rVolume(e),cell:e=>esc(compact(rVolume(e)))},
      {k:'media',lab:'Media',w:'70px',ttl:'How much this is being written about (0-100, editorial judgement, not a count)',
       get:e=>e.att.media,cell:e=>meter(e.att.media)},
      {k:'policy',lab:'Policy',w:'70px',ttl:'How much this is being legislated about (0-100, editorial judgement, not a count)',
       get:e=>e.att.policy,cell:e=>meter(e.att.policy)},
      {k:'ser',lab:'5 yr',w:'64px',cls:'ch',ttl:'Price against its baseline over the series',
       get:e=>rTrend(e),cell:(e,_r,col)=>spark(e,col,62,20)},
    ],
    hay:e=>[e.id,e.n,e.pn,e.th,CATS[e.cat],...e.bar.map(b=>BARS[b]),...e.conc.sup.map(s=>s.n||s.id||'')],
  },
  micro:{
    set:MICRO,cats:MCATS,ccol:MCAT,bars:MBARS,barwhy:MBARWHY,asof:MICRO_ASOF,
    score:microScore,prov:microProv,mult:mMult,
    cols:[
      {k:'score',lab:'#',w:'34px',cls:'rk',ttl:'Overall score: 30% payback, 24% gap, 20% speed to start, 16% take, 10% how hard to copy',
       get:e=>microScore(e),cell:(e,rank)=>String(rank[e.id])},
      {k:'name',lab:'Niche',w:'minmax(140px,1fr)',cls:'nm',txt:1,get:e=>e.pn,cell:e=>nameCell(e)},
      {k:'px',lab:'$',w:'82px',ttl:'What a buyer pays today',get:e=>e.px.v,cell:e=>esc(rPrice(e.px.v,e.u))},
      {k:'gap',lab:'Gap',w:'56px',ttl:'Price over what it would cost if supply could respond',
       get:e=>mMult(e),cell:e=>mMult(e).toFixed(1)+'×'},
      {k:'entry',lab:'To start',w:'72px',ttl:'Capital needed before the first invoice — lower is better, so this column sorts ascending first',
       asc:1,get:e=>e.entry.v,cell:e=>esc(mk(e.entry.v))},
      {k:'pay',lab:'Payback',w:'72px',ttl:'Months of billing to repay the start-up cost — lower is better',
       asc:1,get:e=>mPayback(e),cell:e=>Math.round(mPayback(e))+' mo'},
      {k:'take',lab:'Take / yr',w:'76px',ttl:'What one to five people could bill in a year',
       get:e=>e.take.v,cell:e=>esc(mk(e.take.v))},
      {k:'media',lab:'Media',w:'70px',ttl:'How much this is being written about (0-100, editorial judgement, not a count)',
       get:e=>e.att.media,cell:e=>meter(e.att.media)},
      {k:'policy',lab:'Policy',w:'70px',ttl:'How much this is being legislated about (0-100, editorial judgement, not a count)',
       get:e=>e.att.policy,cell:e=>meter(e.att.policy)},
      {k:'ser',lab:'5 yr',w:'64px',cls:'ch',ttl:'Price against its baseline over the series',
       get:e=>rTrend(e),cell:(e,_r,col)=>spark(e,col,62,20)},
    ],
    hay:e=>[e.id,e.n,e.pn,e.th,MCATS[e.cat],...e.bar.map(b=>MBARS[b]),...e.who,...e.need],
  },
};
const B=()=>BOARDS[rScale];
// Filter state is per board: the two category enums both contain "materials"
// and "regulated", so a single flat map would cross-wire them.
const rCatOn={big:{},micro:{}},rBarOn={big:{},micro:{}};
Object.keys(CATS).forEach(k=>rCatOn.big[k]=1);
Object.keys(BARS).forEach(k=>rBarOn.big[k]=1);
Object.keys(MCATS).forEach(k=>rCatOn.micro[k]=1);
Object.keys(MBARS).forEach(k=>rBarOn.micro[k]=1);

function rMatch(e,q){
  if(!q)return true;
  return B().hay(e).join(' ').toLowerCase().includes(q);
}
// Barrier filter is ANY-match: an entry stuck behind three barriers stays
// visible while any one of them is still selected.
const rCol=k=>B().cols.find(c=>c.k===k)||B().cols[0];
const rVis=()=>{
  const c=rCol(rSort);
  return B().set.filter(e=>rCatOn[rScale][e.cat]&&e.bar.some(b=>rBarOn[rScale][b])&&rMatch(e,rQ))
    .sort((a,b)=>{
      const x=c.get(a),y=c.get(b);
      return (c.txt?String(x).localeCompare(String(y)):x-y)*rDir;
    });
};
// Rank is always by score and always over the FULL set, so a filtered view
// still shows each signal's true position on the board.
const rRankAll=()=>{const b=B(),o=[...b.set].sort((x,y)=>b.score(y)-b.score(x));return Object.fromEntries(o.map((e,i)=>[e.id,i+1]));};
const rById=id=>B().set.find(e=>e.id===id);

const appEl=document.getElementById('app');
// push: true pushes a history entry, false replaces in place, null skips the
// hash write entirely — for a switch that is immediately followed by another
// action that will push (e.g. a supplier jump calling selectNode). Replacing
// there would overwrite the board entry the user needs to come back to.
function setTab(v,push){
  tab=v==='rents'?'rents':'map';
  appEl.dataset.view=tab;
  document.querySelectorAll('#viewTab button').forEach(b=>{const on=b.dataset.v===tab;b.classList.toggle('on',on);b.setAttribute('aria-selected',on?'true':'false');});
  document.getElementById('logoSub').textContent=tab==='rents'?'· the scarcity board':'· global capital-flow map';
  if(tab==='map'){startMapLoop();}
  else{stopMapLoop();buildRentBoard();;}
  if(push!==null)syncHash(push);
}
document.querySelectorAll('#viewTab button').forEach(b=>b.onclick=()=>setTab(b.dataset.v,true));

function buildRentBoard(){syncScaleTab();buildRentFilters();buildRentList();refreshRentStats();if(!rSel)renderRentEmpty();}
// The switch is also set by the hash, so its pressed state is derived here
// rather than only in its own click handler — a deep link into the micro board
// used to leave "Industrial" highlighted above a board titled Within Reach.
function syncScaleTab(){
  document.querySelectorAll('#rScaleTab button').forEach(x=>{const on=x.dataset.sc===rScale;
    x.classList.toggle('on',on);x.setAttribute('aria-selected',on?'true':'false');});
}

function buildRentFilters(){
  // Plain typographic rows, not bordered pills. Ten colour-filled chips with
  // count badges is what made the rail read as a debug widget rather than the
  // contents page of something written.
  const b=B();
  const cc={};b.set.forEach(e=>cc[e.cat]=(cc[e.cat]||0)+1);
  document.getElementById('rcats').innerHTML=Object.keys(b.cats).map(k=>
    `<button class="fr ${rCatOn[rScale][k]?'on':''}" data-rc="${k}" aria-pressed="${rCatOn[rScale][k]?'true':'false'}"><span class="d" style="background:${b.ccol[k]}"></span><span class="t">${esc(b.cats[k])}</span><span class="ct">${cc[k]||0}</span></button>`).join('');
  const bc={};b.set.forEach(e=>e.bar.forEach(k=>bc[k]=(bc[k]||0)+1));
  document.getElementById('rbars').innerHTML=Object.keys(b.bars).map(k=>
    `<button class="fr ${rBarOn[rScale][k]?'on':''}" data-rb="${k}" aria-pressed="${rBarOn[rScale][k]?'true':'false'}"><span class="t">${esc(b.bars[k])}</span><span class="ct">${bc[k]||0}</span></button>`).join('');
  // The fold is closed by default, so the summary has to say when something
  // inside is actually filtering — otherwise a narrowed board looks unexplained.
  // Every barrier starts on, so "all on" is the neutral state and stays quiet.
  const off=Object.keys(b.bars).filter(k=>!rBarOn[rScale][k]).length;
  const cv=document.getElementById('rbarcv');
  cv.textContent=off?`${off} off`:`${Object.keys(b.bars).length}`;
  cv.style.color=off?'var(--accent)':'';
  document.querySelectorAll('[data-rc]').forEach(n=>n.onclick=()=>{rCatOn[rScale][n.dataset.rc]=!rCatOn[rScale][n.dataset.rc];buildRentBoard();syncHash(false);});
  document.querySelectorAll('[data-rb]').forEach(n=>n.onclick=()=>{rBarOn[rScale][n.dataset.rb]=!rBarOn[rScale][n.dataset.rb];buildRentBoard();syncHash(false);});
}

/* The row reads as a sentence, and every clause of it is derived — nothing here
   is a second copy of a number that could drift from the one in the dossier.
   The only prose the data file carries is `pn`, the plain name; the rest is
   assembled from the same fields the score and the inspector read. */
// Snapshot month plus months-to-relief, rounded to the year. Deliberately
// hedged in the copy ("around 2029") — ttr is an estimate on most entries and
// a bare year would read as a promise.
function reliefYear(e){
  const [y,m]=RENT_ASOF.split('-').map(Number);
  const t=new Date(Date.UTC(y,m-1+e.ttr.mo,1));
  return t.getUTCFullYear();
}
// Units read "$ per GB of stacked DRAM" or "$M premium per shop visit". Split
// them: the currency (and any multiplier) belongs on the number, the
// denominator belongs under it. A bare "20.0" in the price slot is not a price.
function rPrice(v,u){
  const m=/^\$([A-Za-z]?)/.exec(u);
  // Prices get their own scale rather than rnum's: money below three figures
  // always carries two decimals, so a column never mixes $20.0 with $9.50.
  const n=v>=1000?Math.round(v).toLocaleString('en-US'):v>=100?v.toFixed(0):v.toFixed(2);
  return '$'+n+(m&&m[1]?m[1]:'');
}
const rUnit=u=>{const m=/\bper\s+(.+)$/i.exec(u);return m?'per '+m[1]:u.replace(/^\$[A-Za-z]?\s*/,'');};
const mk=v=>v>=1000?'$'+(v/1000).toFixed(1)+'M':'$'+Math.round(v)+'K';

/* Row chart. Inline SVG rather than a canvas: 26 of these need no lifecycle,
   no DPR handling and no redraw on tab switch, and they stay crisp when the
   browser zooms. The dashed line is the baseline — the whole point of the
   picture is the gap between the trace and that line. */
function spark(e,col,w=168,h=40){
  const s=e.ser;if(!s||s.length<2)return '';
  const vs=s.map(p=>p.v),lo=Math.min(...vs,e.base.v),hi=Math.max(...vs,e.base.v);
  const pad=(hi-lo)*0.12||1,mn=lo-pad,mx=hi+pad;
  const X=i=>(i/(s.length-1)*(w-2)+1),Y=v=>h-3-((v-mn)/(mx-mn))*(h-6);
  const line=s.map((p,i)=>`${i?'L':'M'}${X(i).toFixed(1)} ${Y(p.v).toFixed(1)}`).join(' ');
  const area=`${line} L${X(s.length-1).toFixed(1)} ${h} L${X(0).toFixed(1)} ${h} Z`;
  const by=Y(e.base.v).toFixed(1),id='g'+e.id;
  return `<svg class="spk" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" role="img"
      aria-label="Price from ${esc(s[0].t)} to ${esc(s[s.length-1].t)}, against the baseline">
    <defs><linearGradient id="${id}" x1="0" x2="0" y1="0" y2="1">
      <stop offset="0" stop-color="${col}" stop-opacity=".28"/><stop offset="1" stop-color="${col}" stop-opacity="0"/>
    </linearGradient></defs>
    <path d="${area}" fill="url(#${id})"/>
    <line x1="0" y1="${by}" x2="${w}" y2="${by}" stroke="currentColor" stroke-width="1" stroke-dasharray="2 3" opacity=".55"/>
    <path d="${line}" fill="none" stroke="${col}" stroke-width="1.6" stroke-linejoin="round" stroke-linecap="round"/>
    <circle cx="${X(s.length-1).toFixed(1)}" cy="${Y(vs[vs.length-1]).toFixed(1)}" r="2.4" fill="${col}"/>
  </svg>`;
}
/* Compact magnitudes for the volume column: 1.9B, 57M, 340K. */
function compact(v){
  if(!isFinite(v)||v<=0)return '—';
  const u=[[1e12,'T'],[1e9,'B'],[1e6,'M'],[1e3,'K']];
  for(const [d,sfx] of u)if(v>=d)return (v/d).toFixed(v/d>=100?0:1)+sfx;
  return String(Math.round(v));
}
/* Attention cells. A 0-100 judgement is easier to compare as a bar than as a
   number, and the bar quietly signals "rating", not "measurement". */
const meter=v=>`<span class="meter" title="${v} of 100"><i style="width:${v}%"></i></span>`;
const nameCell=e=>`<span class="cdot" style="background:${B().ccol[e.cat]}"></span><span class="t" title="${esc(e.pn)} · ${esc(e.n)}">${esc(e.pn)}</span>`;

function buildRentList(){
  const rows=rVis(),rank=rRankAll(),el=document.getElementById('rlist'),b=B();
  const grid=b.cols.map(c=>c.w).join(' ');
  const head=`<div class="thead" style="grid-template-columns:${grid}" role="row">`+b.cols.map(c=>{
    const on=rSort===c.k;
    return `<button class="th ${c.cls||''} ${on?'on':''}" data-sc-col="${c.k}" role="columnheader"
      aria-sort="${on?(rDir<0?'descending':'ascending'):'none'}" title="${esc(c.ttl||c.lab)}"
      >${esc(c.lab)}<i class="ar">${on?(rDir<0?'▾':'▴'):''}</i></button>`;}).join('')+'</div>';
  if(!rows.length){
    el.innerHTML=head+'<div class="rempty">Nothing matches those filters.<br>Switch a category back on to bring the board back.</div>';
    bindHeaders();return;
  }
  el.innerHTML=head+`<div class="tbody" role="rowgroup">`+rows.map(e=>{
    const col=b.ccol[e.cat];
    return `<div class="trow ${rSel===e.id?'on':''}" style="grid-template-columns:${grid}" role="row" tabindex="0"
      aria-selected="${rSel===e.id?'true':'false'}" data-r="${e.id}"
      aria-label="${esc(e.pn)}, ${rPrice(e.px.v,e.u)} ${esc(rUnit(e.u))}, ${b.mult(e).toFixed(1)} times baseline">`
      +b.cols.map(c=>`<div class="td ${c.cls||''}" role="gridcell">${c.cell(e,rank,col)}</div>`).join('')
      +'</div>';}).join('')+'</div>';
  el.querySelectorAll('[data-r]').forEach(r=>{const go=()=>selectRent(r.dataset.r,true);r.onclick=go;
    r.onkeydown=ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();go();}};});
  bindHeaders();
}
/* Clicking a header sorts by it. First click takes the column's natural
   direction — descending for "more is more", ascending for cost and payback
   where lower is the better result — and clicking again flips it. */
function bindHeaders(){
  document.querySelectorAll('[data-sc-col]').forEach(n=>n.onclick=()=>{
    const c=rCol(n.dataset.scCol);
    if(rSort===c.k)rDir=-rDir; else{rSort=c.k;rDir=c.asc?1:(c.txt?1:-1);}
    buildRentList();syncHash(false);
  });
}

function refreshRentStats(){
  const rows=rVis(),b=B(),micro=rScale==='micro';
  const hRN=document.getElementById('hRN'),hRP=document.getElementById('hRP'),hRT=document.getElementById('hRT');
  hRN.textContent=rows.length;
  if(micro){
    hRP.textContent=rows.length?mk(Math.round(rows.reduce((a,e)=>a+e.take.v,0)/rows.length)):'—';
    const en=rows.map(e=>e.entry.v).sort((x,y)=>x-y);
    hRT.textContent=en.length?mk(en[en.length>>1]):'—';
  }else{
    hRP.textContent=fmt(rows.reduce((a,e)=>a+e.pool.v,0));
    const mos=rows.map(e=>e.ttr.mo).sort((x,y)=>x-y);
    hRT.textContent=mos.length?rmo(mos[mos.length>>1]):'—';
  }
  document.querySelectorAll('[data-hlab]').forEach(n=>{n.textContent=n.dataset[micro?'m':'g'];});
  document.getElementById('rttl').textContent=micro?'The Small-Operator Board':'The Scarcity Board';
  document.getElementById('rsub').textContent=micro
    ?`The same thing at a size one person or a small team could actually take on. The barrier is a certification, a skill or a machine — not a fab. ${MICRO.length} of them. Sort by any column.`
    :`Things that cost far more than they should, because nobody can make more of them yet. ${RENTS.length} of them, ${ARCHIVE.length} more already back down. Sort by any column.`;
  // Same idea as the map's provenance mix: what share of what is on screen
  // rests on figures we could actually verify.
  const wt=e=>micro?e.mkt.v:e.pool.v;
  const mix={R:0,E:0,I:0};rows.forEach(e=>mix[b.prov(e)]+=wt(e));
  const tot=mix.R+mix.E+mix.I||1;
  document.getElementById('rprovmix').innerHTML=['R','E','I'].map(k=>
    `<div class="mixrow"><div class="h"><b style="color:${PCOL[k]}">${PNAME[k]}</b><span>${(mix[k]/tot*100).toFixed(0)}%</span></div><div class="track"><i style="width:${mix[k]/tot*100}%;background:${PCOL[k]}"></i></div></div>`).join('')+
    `<div class="note">${micro
      ?'Weighted by the size of each niche. Nothing on this board is a published price — small-lot work is quoted bilaterally and never printed. These are modelled well enough to rank, not well enough to underwrite. Do your own diligence before spending money.'
      :'Share of visible rent pool by the weakest figure behind each signal. Contract prices for packaging slots, CDMO lines and bilateral isotope supply are not publicly quoted — most of this board is modeled, and says so.'}</div>`;
}

function renderRentEmpty(){
  document.getElementById('rinspector').innerHTML='<div class="ins-empty"><div class="big" aria-hidden="true">△</div>Pick one to see what it costs now, what it used to cost, who is collecting the difference, why nobody can simply make more, and what would bring the price back down.<div class="note" style="margin-top:12px">The order is worked out from the numbers, not chosen by hand. <a href="#about" id="rabLink" style="color:var(--accent)">How it is ranked</a></div></div>';
  const l=document.getElementById('rabLink');if(l)l.onclick=ev=>{ev.preventDefault();openAbout();};
}


/* The micro inspector leads with the three numbers a person weighing this up
   actually needs — what to spend, how long until money comes in, and what it
   pays back — before any of the market framing. */
function renderMicroInspector(e){
  const p=microProv(e),rank=rRankAll()[e.id];
  document.getElementById('rinspector').innerHTML=`
   <div class="ihead"><div class="tk">No. ${rank} of ${MICRO.length}</div><div class="nm">${esc(e.n)}</div>
     <div class="meta"><span class="pill"><span class="d" style="background:${MCAT[e.cat]}"></span>${esc(MCATS[e.cat])}</span><span class="pill" title="Unit the price is quoted in">${esc(e.u)}</span></div></div>
   <div class="stats">
     <div class="stat"><div class="k">Cost to start</div><div class="v">${mk(e.entry.v)}<span class="tag ${e.entry.p}">${PWORD[e.entry.p]}</span></div><div class="k" style="margin-top:2px">${esc(e.entry.m)}</div></div>
     <div class="stat"><div class="k">Until the first invoice</div><div class="v">${e.ramp.mo} mo<span class="tag ${e.ramp.p}">${PWORD[e.ramp.p]}</span></div><div class="k" style="margin-top:2px">${esc(e.ramp.m)}</div></div>
     <div class="stat"><div class="k">A year of billing</div><div class="v">${mk(e.take.v)}<span class="tag ${e.take.p}">${PWORD[e.take.p]}</span></div><div class="k" style="margin-top:2px">one to five people</div></div>
     <div class="stat"><div class="k">Pays itself back in</div><div class="v">${Math.round(mPayback(e))} mo</div><div class="k" style="margin-top:2px">start-up cost over billing</div></div>
     <div class="stat"><div class="k">Costs this much more</div><div class="v">${mMult(e).toFixed(1)}×<span class="tag ${e.px.p}">${PWORD[e.px.p]}</span></div><div class="k" style="margin-top:2px">${rPrice(e.px.v,e.u)} now, ${rPrice(e.base.v,e.u)} if supply could respond</div></div>
     <div class="stat"><div class="k">Whole niche is worth</div><div class="v">${mk(e.mkt.v)}<span class="tag ${e.mkt.p}">${PWORD[e.mkt.p]}</span></div><div class="k" style="margin-top:2px">a year, everyone in it combined</div></div>
   </div>
   <div class="nsw"><div class="k">Price · ${esc(e.u)}</div><canvas id="rspark" aria-label="Price history for ${esc(e.n)}"></canvas><div class="yrs"><span>${esc(e.ser[0].t)}</span><span>${esc(e.ser[e.ser.length-1].t)}</span></div></div>
   <dl class="minor">${[['Last year',(rTrend(e)>0?'+':'')+(rTrend(e)*100).toFixed(0)+'%'],
      ['Barriers',String(e.bar.length)],['Ways round',String(e.sub.length)],
      ['Units a year',compact(mVolume(e))],
      ['Media',String(e.att.media)+'/100'],['Policy',String(e.att.policy)+'/100']]
      .map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>
   <button class="ddbtn" id="openDossier">Full dossier →</button>
   <div class="verdict warn">Nothing on this board is a published price — work at this size is quoted bilaterally and never printed. ${esc(e.take.m)} Modelled well enough to rank, not well enough to underwrite. Check it yourself before you spend anything.</div>
   <div class="flowsec"><div class="lbl">What is going on</div><div style="font-size:12.5px;line-height:1.6;color:var(--dim)">${esc(e.th)}</div></div>
   <div class="flowsec" style="border-top:1px solid var(--line)"><div class="lbl">What you actually need <span>${e.need.length}</span></div>
     ${e.need.map(n=>`<div class="prov-txt" style="margin:0 0 8px">${esc(n)}</div>`).join('')}</div>
   <div class="flowsec" style="border-top:1px solid var(--line)"><div class="lbl">Who buys it <span>${e.who.length}</span></div>
     ${e.who.map(w=>`<div class="rkv"><span class="k">${esc(w)}</span></div>`).join('')}</div>
   <div class="flowsec" style="border-top:1px solid var(--line)"><div class="lbl">Why it stays expensive <span>${e.bar.length}</span></div>
     ${e.bar.map(b=>`<div class="rkv"><span class="k">${esc(MBARS[b])}</span></div>`).join('')}</div>
   <div class="mblock"><div class="lbl">What would end it</div>
     ${e.kill.map(k=>`<div class="prov-txt" style="margin:0 0 8px">${esc(k)}</div>`).join('')}
     <div class="meth" style="color:var(--mut);font-size:11px;margin-top:6px">Provenance: ${PNAME[p]} at its weakest figure.</div></div>`;
  const btn=document.getElementById('openDossier');if(btn)btn.onclick=()=>openDossier(e.id);
}

function selectRent(id,push){
  const e=rById(id);if(!e)return;
  rSel=id;
  if(rScale==='micro'){renderMicroInspector(e);drawRSpark(e);buildRentList();syncHash(push);return;}
  const p=rProv(e),rank=rRankAll()[id],mult=rMult(e),an=e.an?ABY[e.an]:null;
  const supRow=s=>{const c=s.id&&byId[s.id];
    return `<div class="rsup"><span style="width:9px;height:9px;border-radius:50%;background:${c?SEC[c.sec]:'var(--mut)'};display:inline-block"></span>${c?`<span class="cplink" data-go="${s.id}" role="button" tabindex="0" title="Show ${esc(c.name)} on the map">${esc(c.name)}</span>`:`<span class="plain">${esc(s.n||s.id)}</span>`}<span class="sh">${rpct(s.sh)}</span></div>`;};
  document.getElementById('rinspector').innerHTML=`
   <div class="ihead"><div class="tk">No. ${rank} of ${RENTS.length}</div><div class="nm">${esc(e.n)}</div>
     <div class="meta"><span class="pill"><span class="d" style="background:${RCAT[e.cat]}"></span>${esc(CATS[e.cat])}</span><span class="pill" title="Unit the price is quoted in">${esc(e.u)}</span></div></div>
   <div class="stats">
     <div class="stat"><div class="k">Costs this much more</div><div class="v">${mult.toFixed(1)}×<span class="tag ${e.px.p}">${PWORD[e.px.p]}</span></div><div class="k" style="margin-top:2px">${rPrice(e.px.v,e.u)} now, ${rPrice(e.base.v,e.u)} before</div></div>
     <div class="stat"><div class="k">Excess paid every year</div><div class="v">${fmt(e.pool.v)}<span class="tag ${e.pool.p}">${PWORD[e.pool.p]}</span></div><div class="k" style="margin-top:2px">above what it used to cost</div></div>
     <div class="stat"><div class="k">Until it eases</div><div class="v">${rmo(e.ttr.mo)}<span class="tag ${e.ttr.p}">${PWORD[e.ttr.p]}</span></div><div class="k" style="margin-top:2px">${e.ttr.mo>=96?'no end in sight':'around '+reliefYear(e)}</div></div>
     <div class="stat"><div class="k">Held by the top three</div><div class="v">${rpct(e.conc.top3)}<span class="tag ${e.conc.p}">${PWORD[e.conc.p]}</span></div></div>
     <div class="stat"><div class="k">Their gross margin</div><div class="v">${rpct(e.gm.v)}<span class="tag ${e.gm.p}">${PWORD[e.gm.p]}</span></div><div class="k" style="margin-top:2px">${esc(byId[e.gm.who]?byId[e.gm.who].name:e.gm.who)}</div></div>
     <div class="stat"><div class="k">Where it ranks</div><div class="v">No. ${rank}</div><div class="k" style="margin-top:2px">of ${RENTS.length} on the board</div></div>
   </div>
   <div class="nsw"><div class="k">Price · ${esc(e.u)}</div><canvas id="rspark" aria-label="Price history for ${esc(e.n)}"></canvas><div class="yrs"><span>${esc(e.ser[0].t)}</span><span>${esc(e.ser[e.ser.length-1].t)}</span></div></div>
   <dl class="minor">${[['Last year',(rTrend(e)>0?'+':'')+(rTrend(e)*100).toFixed(0)+'%'],
      ['Years high',String(rRun(e))],['Biggest swing',(rVol(e)*100).toFixed(0)+'%'],
      ['Ways round',String(rSubs(e))],['Barriers',String(rBars(e))],
      ['Media',String(e.att.media)+'/100'],['Policy',String(e.att.policy)+'/100']]
      .map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>
   <button class="ddbtn" id="openDossier">Full dossier →</button>
   ${p==='R'?`<div class="verdict ok">Every headline number here comes from a published source. That is rare on this board — most of these things are sold under private contracts and the prices are never printed anywhere.</div>`
      :`<div class="verdict warn">The softest number here is ${p==='E'?'an estimate':'a model'}, not something published. ${esc(e.pool.m)} So read the position on this list as a rough guide, not a measurement.</div>`}
   <div class="flowsec"><div class="lbl">What is going on</div><div style="font-size:12.5px;line-height:1.6;color:var(--dim)">${esc(e.th)}</div></div>
   <div class="flowsec" style="border-top:1px solid var(--line)"><div class="lbl">Who collects it <span>${e.conc.sup.length}</span></div>${e.conc.sup.map(supRow).join('')}
     <div class="meth" style="color:var(--mut);font-size:11px;margin-top:8px">${esc(e.conc.s)}. Named suppliers already on the map are clickable.</div></div>
   <div class="flowsec" style="border-top:1px solid var(--line)"><div class="lbl">Why nobody can just make more <span>${e.bar.length}</span></div>
     ${e.bar.map(b=>`<div class="rkv"><span class="k">${esc(BARS[b])}</span></div>`).join('')}
     <div class="meth" style="color:var(--mut);font-size:11px;margin-top:8px">${esc(e.ttr.m)}</div></div>
   ${an?`<div class="mblock"><div class="lbl">It happened before</div><div class="rkv"><span class="k">${esc(an.n)}</span><span class="v">${rnum(an.peak.v)} → ${rnum(an.trough.v)}</span></div><div class="prov-txt"><b>Lesson.</b> ${esc(an.lesson)}</div></div>`:''}`;
  const b=document.getElementById('openDossier');if(b)b.onclick=()=>openDossier(id);
  // Skip the tab's own hash write and let selectNode push the one entry — so a
  // single Back returns to this signal on the board, not to a half-state.
  document.querySelectorAll('#rinspector .cplink').forEach(s=>{const go=()=>{setTab('map',null);selectNode(s.dataset.go);};s.onclick=go;s.onkeydown=ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();go();}};});
  drawRSpark(e);
  buildRentList();
  
  syncHash(push);
}

function drawRSpark(e){
  const cv=document.getElementById('rspark');if(!cv||!e.ser.length)return;
  const g=cv.getContext('2d'),w=cv.clientWidth||300,h=46;
  cv.width=Math.round(w*DPR);cv.height=Math.round(h*DPR);g.setTransform(DPR,0,0,DPR,0,0);
  const vs=e.ser.map(d=>d.v),lo=Math.min(...vs,e.base.v),hi=Math.max(...vs);
  const X=i=>10+(e.ser.length===1?0.5:i/(e.ser.length-1))*(w-20),Y=v=>h-8-((v-lo)/((hi-lo)||1))*(h-18);
  // Baseline first, as a dashed floor — the whole point is the gap above it.
  g.strokeStyle=PCOL.E;g.globalAlpha=0.5;g.setLineDash([4,4]);g.lineWidth=1;
  g.beginPath();g.moveTo(8,Y(e.base.v));g.lineTo(w-8,Y(e.base.v));g.stroke();
  g.setLineDash([]);g.globalAlpha=1;
  g.strokeStyle=RCAT[e.cat];g.lineWidth=1.8;g.beginPath();
  e.ser.forEach((d,i)=>i?g.lineTo(X(i),Y(d.v)):g.moveTo(X(i),Y(d.v)));g.stroke();
  g.fillStyle=RCAT[e.cat];e.ser.forEach((d,i)=>{g.beginPath();g.arc(X(i),Y(d.v),2,0,6.28);g.fill();});
  const li=e.ser.length-1;
  g.fillStyle='#fff';g.beginPath();g.arc(X(li),Y(e.ser[li].v),3.2,0,6.28);g.fill();
  g.font='600 10px Inter,sans-serif';g.textAlign='right';g.fillStyle='#e8eef7';
  g.fillText(rnum(e.ser[li].v),w-10,Math.max(10,Y(e.ser[li].v)-8));
  g.textAlign='left';g.fillStyle=PCOL.E;g.fillText('baseline '+rnum(e.base.v),10,Math.min(h-2,Y(e.base.v)+11));
}

window.addEventListener('resize',()=>{if(rSel&&rById(rSel))drawRSpark(rById(rSel));});
const rsrch=document.getElementById('rsrch');
/* Scale switch. Selection, sort and filters are per board, so moving between
   them resets the selection rather than carrying a dangling id across. */
document.querySelectorAll('#rScaleTab button').forEach(btn=>btn.onclick=()=>{
  const v=btn.dataset.sc==='micro'?'micro':'big';
  if(v===rScale)return;
  rScale=v;rSel=null;rSort='score';rDir=-1;rQ='';rsrch.value='';
  buildRentBoard();syncHash(true);
});

rsrch.oninput=()=>{rQ=rsrch.value.toLowerCase().trim();buildRentList();refreshRentStats();;};
rsrch.onkeydown=ev=>{if(ev.key==='Escape'){ev.stopPropagation();rsrch.value='';rQ='';buildRentList();refreshRentStats();;}};

/* ---- dossier modal (the long-form breakdown) ---- */
const rentModal=document.getElementById('rentModal');
let rdPrevFocus=null;
function provRow(label,f,extra){
  return `<tr><td>${esc(label)}</td><td><span class="tag ${f.p}">${PNAME[f.p]}</span> · source quality ${(f.c*100|0)}%${extra?' · '+esc(extra):''}<br>${f.m?'<b>Method.</b> '+esc(f.m)+'<br>':''}<b>Source.</b> ${esc(f.s)}${f.url?` · <a href="${esc(f.url)}" target="_blank" rel="noopener noreferrer" style="color:var(--accent)">verify ↗</a>`:''}</td></tr>`;
}

/* Micro dossier. Same long-form treatment as the industrial one, organised
   around doing the thing rather than around the market for it. */
function openMicroDossier(e){
  const p=microProv(e);
  document.getElementById('rdTitle').textContent=e.n;
  document.getElementById('rdBody').innerHTML=`
   <p style="color:var(--txt);font-size:13.5px;line-height:1.6;margin:0 0 14px">${esc(e.th)}</p>
   <div class="mblock"><div class="lbl">The numbers</div>
     ${[['What buyers pay',`${rPrice(e.px.v,e.u)} ${rUnit(e.u)}`,e.px],
        ['What it would cost if supply could respond',`${rPrice(e.base.v,e.u)} · ${e.base.per}`,e.base],
        ['Whole niche, a year',mk(e.mkt.v),e.mkt],
        ['A year of billing, one to five people',mk(e.take.v),e.take],
        ['Cost to start',mk(e.entry.v),e.entry],
        ['Months to the first invoice',String(e.ramp.mo),e.ramp]]
       .map(([k,v,f])=>`<div class="rkv"><span class="k">${esc(k)}</span><span class="v">${esc(v)} <span class="tag ${f.p}">${PWORD[f.p]}</span></span></div>
         <div class="prov-txt">${esc(f.m)} <i style="color:var(--mut)">${esc(f.s)}</i></div>`).join('')}</div>
   <div class="mblock"><div class="lbl">What you actually need</div>
     ${e.need.map(n=>`<div class="prov-txt" style="margin:0 0 8px">${esc(n)}</div>`).join('')}</div>
   <div class="mblock"><div class="lbl">Why it stays expensive</div>
     ${e.bar.map(b=>`<div class="rkv"><span class="k">${esc(MBARS[b])}</span></div><div class="prov-txt">${esc(MBARWHY[b])}</div>`).join('')}</div>
   <div class="mblock"><div class="lbl">Who buys it</div>
     ${e.who.map(w=>`<div class="rkv"><span class="k">${esc(w)}</span></div>`).join('')}</div>
   <div class="mblock"><div class="lbl">What would end it</div>
     ${e.kill.map(k=>`<div class="prov-txt" style="margin:0 0 8px">${esc(k)}</div>`).join('')}</div>
   <div class="mblock"><div class="lbl">If this one closes</div>
     ${e.sub.map(x=>`<div class="rkv"><span class="k">${esc(x)}</span></div>`).join('')}</div>`;
  document.getElementById('rdFoot').innerHTML=`No. ${rRankAll()[e.id]} of ${MICRO.length} · score ${microScore(e).toFixed(0)} = 30% payback + 24% how overpriced + 20% speed to start + 16% annual take + 10% how hard to copy, computed from the fields above. Snapshot ${esc(MICRO_ASOF)}. Weakest figure here is ${PNAME[p]}. Nothing on this board is a published price — check every number yourself before you spend money on it.`;
  rentModal.classList.add('show');document.getElementById('rdClose').focus();
}

function openDossier(id){
  const e=rById(id);if(!e)return;
  rdPrevFocus=document.activeElement;
  if(rScale==='micro')return openMicroDossier(e);
  const an=e.an?ABY[e.an]:null;
  document.getElementById('rdTitle').textContent=e.n;
  document.getElementById('rdBody').innerHTML=`
   <p style="color:var(--txt);font-size:13.5px;line-height:1.6;margin:0 0 14px">${esc(e.th)}</p>
   <div class="dgrid">
     <div class="dcell"><div class="k">Price now</div><div class="v">${rnum(e.px.v)}</div><div class="sub">${esc(e.u)} · as of ${esc(e.px.asOf)}</div></div>
     <div class="dcell"><div class="k">Baseline</div><div class="v">${rnum(e.base.v)}</div><div class="sub">${esc(e.base.per)}</div></div>
     <div class="dcell"><div class="k">Rent multiple</div><div class="v">${rMult(e).toFixed(1)}×</div><div class="sub">price ÷ baseline, derived</div></div>
     <div class="dcell"><div class="k">Rent pool</div><div class="v">${fmt(e.pool.v)}</div><div class="sub">per year of excess over baseline</div></div>
   </div>
   <h4>Why supply can't respond</h4>
   <ul>${e.bar.map(b=>`<li><b>${esc(BARS[b])}.</b> ${esc(BARWHY[b])}</li>`).join('')}</ul>
   <h4>Time to relief · ${rmo(e.ttr.mo)}</h4>
   <p>${esc(e.ttr.m)}</p>
   <p>${esc(e.build)}</p>
   <h4>What solving it requires</h4>
   <ul>${e.solve.map(s=>`<li>${esc(s)}</li>`).join('')}</ul>
   <h4>What would kill this rent</h4>
   <ul>${e.kill.map(s=>`<li>${esc(s)}</li>`).join('')}</ul>
   <h4>Substitutes and adjacent routes</h4>
   <p>${e.sub.map(esc).join(' · ')}</p>
   <h4>Who collects it</h4>
   <p>${e.conc.sup.map(s=>`${esc(s.n||(byId[s.id]?byId[s.id].name:s.id))} ${rpct(s.sh)}`).join(' · ')}<br>
     <span style="color:var(--mut)">Top-3 share ${rpct(e.conc.top3)} · HHI ${e.conc.hhi} · incumbent gross margin ${rpct(e.gm.v)} (${esc(e.gm.who)})</span></p>
   ${an?`<h4>Historical analogue · ${esc(an.n)}</h4>
     <p>${rnum(an.peak.v)} (${esc(an.peak.t)}) → ${rnum(an.trough.v)} (${esc(an.trough.t)}). ${esc(an.why)}<br>
     <b>Lesson.</b> ${esc(an.lesson)}</p>`:''}
   <h4>Provenance, figure by figure</h4>
   <table class="dtab">
     ${provRow('Price',e.px,'as of '+e.px.asOf)}
     ${provRow('Baseline',e.base,e.base.per)}
     ${provRow('Rent pool',e.pool)}
     ${provRow('Incumbent margin',e.gm,e.gm.who)}
     ${provRow('Concentration',e.conc)}
     ${provRow('Time to relief',e.ttr)}
   </table>`;
  document.getElementById('rdFoot').innerHTML=`Rank ${rRankAll()[id]} of ${RENTS.length} · score ${rentScore(e).toFixed(0)} = 30% rent multiple + 28% rent pool + 20% persistence + 12% concentration + 10% incumbent margin, computed from the fields above. Snapshot ${esc(RENT_ASOF)}. Estimated and Inferred figures are directional, not audited.`;
  rentModal.classList.add('show');document.getElementById('rdClose').focus();
}
function closeDossier(){rentModal.classList.remove('show');if(rdPrevFocus&&rdPrevFocus.focus){try{rdPrevFocus.focus();}catch{/* element gone */}}}
document.getElementById('rdClose').onclick=closeDossier;
rentModal.addEventListener('mousedown',e=>{if(e.target===rentModal)closeDossier();});
rentModal.addEventListener('keydown',e=>{
  if(e.key!=='Tab'||!rentModal.classList.contains('show'))return;
  const f=[...rentModal.querySelectorAll('button,a[href]')];
  if(!f.length)return;
  const first=f[0],last=f[f.length-1],cur=document.activeElement;
  if(e.shiftKey&&(cur===first||!f.includes(cur))){e.preventDefault();last.focus();}
  else if(!e.shiftKey&&(cur===last||!f.includes(cur))){e.preventDefault();first.focus();}
});

/* ---- shareable URL state ----
   #node=NVDA&t=2022&hide=fin,energy&layers=RE&size=rev — every interesting
   view is linkable. Selection changes push history (back/forward steps
   through nodes); filter/scrub changes replace in place. */
let restoring=false;
function syncHash(push){
  if(restoring)return;
  const p=new URLSearchParams();
  if(selected)p.set('node',selected);
  if(tIdx!==PERIODS.length-1)p.set('t',PERIODS[tIdx]);
  const off=Object.keys(SEC).filter(s=>!secOn[s]);if(off.length)p.set('hide',off.join(','));
  const lay=['R','E','I'].filter(k=>layerOn[k]).join('');if(lay!=='REI')p.set('layers',lay);
  if(sizeBy!=='mcap')p.set('size',sizeBy);
  // Board state rides in the same hash. It is only emitted while the board is
  // the active view, so map links stay as short as they were.
  if(tab==='rents'){
    p.set('view','rents');
    if(rSel)p.set('r',rSel);
    if(rScale!=='big')p.set('scale',rScale);
    if(rDir>0)p.set('rdir','asc');
    const coff=Object.keys(B().cats).filter(k=>!rCatOn[rScale][k]);if(coff.length)p.set('rcat',coff.join(','));
    const boff=Object.keys(B().bars).filter(k=>!rBarOn[rScale][k]);if(boff.length)p.set('rbar',boff.join(','));
    if(rSort!=='score')p.set('rsort',rSort);
  }
  const h=p.toString()?'#'+p.toString():'';
  if(h===location.hash)return;
  if(push)history.pushState(null,'',h||'#');
  else history.replaceState(null,'',h||location.pathname+location.search);
}
function applyHash(){
  const raw=location.hash.slice(1);
  if(raw==='about'){openAbout();return false;}
  if(!raw)return false;
  const p=new URLSearchParams(raw);restoring=true;
  if(p.has('t')){const i=PERIODS.indexOf(p.get('t'));if(i>=0){tIdx=i;scrub.value=i;document.getElementById('period').textContent=PERIODS[i];}}
  Object.keys(SEC).forEach(s=>secOn[s]=true);
  if(p.has('hide'))p.get('hide').split(',').forEach(s=>{if(s in secOn)secOn[s]=false;});
  if(p.has('layers')){const l=p.get('layers');['R','E','I'].forEach(k=>layerOn[k]=l.includes(k));}
  if(p.has('size')&&['mcap','rev'].includes(p.get('size'))){sizeBy=p.get('size');document.querySelectorAll('#sizeBy button').forEach(x=>x.classList.toggle('on',x.dataset.by===sizeBy));}
  buildSectors();buildLayers();refreshStats();
  rScale=p.get('scale')==='micro'?'micro':'big';
  Object.keys(B().cats).forEach(k=>rCatOn[rScale][k]=true);
  if(p.has('rcat'))p.get('rcat').split(',').forEach(k=>{if(k in rCatOn[rScale])rCatOn[rScale][k]=false;});
  Object.keys(B().bars).forEach(k=>rBarOn[rScale][k]=true);
  if(p.has('rbar'))p.get('rbar').split(',').forEach(k=>{if(k in rBarOn[rScale])rBarOn[rScale][k]=false;});
  rSort=p.has('rsort')&&B().cols.some(c=>c.k===p.get('rsort'))?p.get('rsort'):'score';
  rDir=p.get('rdir')==='asc'?1:-1;
  const wantRents=p.get('view')==='rents';
  setTab(wantRents?'rents':'map',false);
  let sel=false;
  if(wantRents){
    const rid=(p.get('r')||'').toUpperCase();
    if(rid&&rById(rid)){selectRent(rid,false);sel=true;}
    else{rSel=null;buildRentBoard();}
  }
  const nid=(p.get('node')||'').toUpperCase(); // ids are uppercase; accept #node=aapl
  if(nid&&byId[nid]){selectNode(nid);sel=true;}
  restoring=false;
  return sel;
}

/* boot */
// The scrubber's range is driven by PERIODS (src/years.js) — the static HTML
// attributes are only a no-JS fallback and must not be the source of truth.
scrub.max=String(PERIODS.length-1);scrub.value=String(tIdx);
scrub.setAttribute('aria-label',`Time period (${PERIODS[0]}–${PERIODS[PERIODS.length-1]})`);
document.getElementById('period').textContent=PERIODS[tIdx];
buildSectors();buildLayers();refreshStats();tick();buildRentBoard();startMapLoop();
const deepLinked=applyHash();
window.addEventListener('hashchange',applyHash);
// Demo-select only when we landed on the map with nothing asked for — a deep
// link into the board must not get its hash rewritten 400ms later.
if(!deepLinked&&tab==='map'&&location.hash!=='#about')setTimeout(()=>selectNode('NVDA'),400);
