/* GENERATED by humans/build.mjs — do not edit.
   Metadata for the ${rows.length}-person US $100M-$5B census. The records
   themselves live in public/humans-data.json and are fetched on demand by
   loadHumans(). Regenerate both with: node humans/build.mjs

   Every derived field (years, vel, ageAt100, since100, band, ageb, u45, y100) is
   computed at build time from the record's own dates, never typed, so the
   arithmetic cannot drift from the source. See humans/README.md. */

export const HASOF = "2026-08";
export const HCOUNT = 557;
export const HBANDS = [{"id":"b1","lo":0.1,"hi":0.25,"n":"$100M - $250M"},{"id":"b2","lo":0.25,"hi":0.5,"n":"$250M - $500M"},{"id":"b3","lo":0.5,"hi":1,"n":"$500M - $1B"},{"id":"b4","lo":1,"hi":2.5,"n":"$1B - $2.5B"},{"id":"b5","lo":2.5,"hi":5,"n":"$2.5B - $5B"}];
export const HAGEBANDS = [{"id":"a1","lo":0,"hi":30,"n":"Under 30"},{"id":"a2","lo":30,"hi":35,"n":"30-34"},{"id":"a3","lo":35,"hi":40,"n":"35-39"},{"id":"a4","lo":40,"hi":45,"n":"40-44"},{"id":"a5","lo":45,"hi":55,"n":"45-54"},{"id":"a6","lo":55,"hi":65,"n":"55-64"},{"id":"a7","lo":65,"hi":200,"n":"65+"}];
export const HREGIONS = {"bay":"SF Bay Area","socal":"Southern California","pnw":"Pacific Northwest","mtn":"Mountain West & Plains","tx":"Texas","mw":"Midwest","se":"Southeast","ne":"Northeast (ex-NYC)","nyc":"New York metro","dc":"DC, Maryland & Virginia"};
export const HSECTORS = {"tech":"Technology","finance":"Finance","industry":"Industry & manufacturing","consumer":"Consumer goods","realestate":"Real estate","energy":"Energy","health":"Health & pharma","media":"Media & entertainment","retail":"Retail","logistics":"Logistics & transport","agri":"Agriculture & food","crypto":"Crypto & digital assets","other":"Other"};
export const HORIGINS = { self: 'Self-made', inherited: 'Inherited', mixed: 'Mixed' };

/* The records, fetched once and cached. Resolves to an array; rejects if the
   page is being opened from disk rather than served, which the caller reports
   rather than swallowing. */
let _rows = null, _inflight = null;
export function loadHumans() {
  if (_rows) return Promise.resolve(_rows);
  if (!_inflight) {
    // Relative to the page, not the module: the production build inlines this
    // module into index.html, and humans-data.json sits beside it — which also
    // resolves correctly when Pages serves the site from a /repo/ subpath.
    _inflight = fetch('humans-data.json')
      .then((r) => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); })
      .then((d) => { _rows = d.rows; return _rows; })
      .catch((e) => { _inflight = null; throw e; });
  }
  return _inflight;
}
