// Unit tests for the $100M-$5B census (src/humans.js) and its derived measures.
// Same spirit as data.test.mjs and rents.test.mjs: the census's credibility rests
// on the arithmetic being computed rather than typed, so these guard the two
// things a research pass can get wrong silently — a figure outside the declared
// scope, and a date that contradicts another date on the same record.
//
// Both halves are GENERATED by humans/build.mjs: src/humans.js carries the
// metadata and ships inside the single-file build, while the records live in
// src/public/humans-data.json and are fetched by the page on demand. These tests
// assert the shipped artefacts together, so a stale or hand-edited one fails here
// rather than in a browser.
// Runs under node's built-in test runner: `npm run test:unit`.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { HCOUNT, HBANDS, HAGEBANDS, HREGIONS, HSECTORS, HORIGINS, HASOF } from '../../src/humans.js';

const DATA = JSON.parse(readFileSync(new URL('../../src/public/humans-data.json', import.meta.url), 'utf8'));
const HUMANS = DATA.rows;

// The two generated halves must describe the same census — a metadata module that
// disagrees with the data file means one of them was regenerated and the other
// was not, which the page would show as a wrong headline count.
test('the metadata module and the data file agree', () => {
  assert.equal(DATA.asof, HASOF, 'as-of dates disagree between the module and the data');
  assert.equal(HCOUNT, HUMANS.length, `HCOUNT says ${HCOUNT}, the data file has ${HUMANS.length}`);
});

const PROVS = new Set(['R', 'E', 'I']);
const REGION_KEYS = new Set(Object.keys(HREGIONS));
const SECTOR_KEYS = new Set(Object.keys(HSECTORS));
const ORIGIN_KEYS = new Set(Object.keys(HORIGINS));
const BAND_IDS = new Set(HBANDS.map((b) => b.id));
const AGEBAND_IDS = new Set(HAGEBANDS.map((b) => b.id));
const ASOF_Y = Number(HASOF.slice(0, 4));

test('the census is non-empty and every id is unique', () => {
  assert.ok(HUMANS.length > 100, `expected a substantial census, got ${HUMANS.length}`);
  const seen = new Set();
  for (const r of HUMANS) {
    assert.match(r.id, /^[A-Z0-9_]+$/, `${r.id}: id must be A-Z 0-9 _`);
    assert.ok(!seen.has(r.id), `duplicate id ${r.id}`);
    seen.add(r.id);
  }
});

test('every net worth sits inside the declared $100M-$5B scope, both ends inclusive', () => {
  for (const r of HUMANS) {
    assert.ok(typeof r.nw === 'number' && Number.isFinite(r.nw), `${r.id}: nw must be a finite number`);
    assert.ok(r.nw >= 0.1 && r.nw <= 5.0, `${r.id}: nw ${r.nw} is outside $100M-$5B`);
  }
});

test('enum fields resolve, and the census is US-only', () => {
  for (const r of HUMANS) {
    assert.ok(PROVS.has(r.p), `${r.id}: bad provenance tier ${r.p}`);
    assert.ok(r.c > 0 && r.c <= 1, `${r.id}: confidence ${r.c} outside (0,1]`);
    assert.ok(REGION_KEYS.has(r.region), `${r.id}: unknown region ${r.region}`);
    assert.ok(SECTOR_KEYS.has(r.sect), `${r.id}: unknown sector ${r.sect}`);
    assert.ok(ORIGIN_KEYS.has(r.origin), `${r.id}: unknown origin ${r.origin}`);
    assert.equal(r.country, 'US', `${r.id}: the census is US-only, got ${r.country}`);
    assert.match(r.state, /^[A-Z]{2}$/, `${r.id}: state must be a USPS code, got ${r.state}`);
  }
});

test('prose fields carry real content and no embedded newlines', () => {
  for (const r of HUMANS) {
    for (const k of ['did', 'why', 'obst', 'turn']) {
      assert.equal(typeof r[k], 'string', `${r.id}: ${k} must be a string`);
      assert.ok(r[k].length >= 20, `${r.id}: ${k} is only ${r[k].length} chars`);
      assert.ok(r[k].length <= 340, `${r.id}: ${k} is ${r[k].length} chars, over the cap`);
      assert.ok(!/\n/.test(r[k]), `${r.id}: ${k} contains a newline`);
    }
    assert.ok(Array.isArray(r.comp) && r.comp.length > 0, `${r.id}: comp must be a non-empty array`);
  }
});

// The check that catches the most research errors, and the one reason this
// census drops otherwise-complete people: a person's age has to agree with the
// year they started and how old they were then.
test('age agrees with started + startAge', () => {
  for (const r of HUMANS) {
    if (r.age == null || r.started == null || r.startAge == null) continue;
    const implied = r.startAge + (ASOF_Y - r.started);
    assert.ok(Math.abs(implied - r.age) <= 2,
      `${r.id}: age ${r.age} disagrees with started ${r.started} + startAge ${r.startAge} (implies ${implied})`);
  }
});

test('dates are plausible and no fortune crosses $100M after the as-of year', () => {
  for (const r of HUMANS) {
    assert.ok(r.started >= 1900 && r.started <= ASOF_Y, `${r.id}: started ${r.started} implausible`);
    assert.ok(r.startAge >= 10 && r.startAge <= 90, `${r.id}: startAge ${r.startAge} implausible`);
    if (r.toFirst100 != null) {
      assert.ok(r.toFirst100 >= 0, `${r.id}: toFirst100 cannot be negative`);
      assert.ok(r.started + r.toFirst100 <= ASOF_Y,
        `${r.id}: crossed $100M in ${r.started + r.toFirst100}, after ${ASOF_Y}`);
    }
  }
});

// Derived measures are computed by the build from the record's own dates. If any
// of these disagree with their inputs, the generated module is stale.
test('derived measures are consistent with the fields they come from', () => {
  const bandOf = (nw) => (HBANDS.find((b) => nw >= b.lo && nw < b.hi) || HBANDS[HBANDS.length - 1]).id;
  const ageBandOf = (a) => (HAGEBANDS.find((b) => a >= b.lo && a < b.hi) || HAGEBANDS[HAGEBANDS.length - 1]).id;
  for (const r of HUMANS) {
    assert.ok(BAND_IDS.has(r.band), `${r.id}: unknown band ${r.band}`);
    assert.equal(r.band, bandOf(r.nw), `${r.id}: band ${r.band} disagrees with nw ${r.nw}`);
    assert.equal(r.years, ASOF_Y - r.started, `${r.id}: years disagrees with started`);
    if (r.age != null) {
      assert.ok(AGEBAND_IDS.has(r.ageb), `${r.id}: unknown age band ${r.ageb}`);
      assert.equal(r.ageb, ageBandOf(r.age), `${r.id}: ageb disagrees with age ${r.age}`);
      assert.equal(r.u45, r.age < 45, `${r.id}: u45 disagrees with age ${r.age}`);
    }
    if (r.toFirst100 != null) {
      assert.equal(r.y100, r.started + r.toFirst100, `${r.id}: y100 disagrees with its inputs`);
      if (r.startAge != null) assert.equal(r.ageAt100, r.startAge + r.toFirst100, `${r.id}: ageAt100 disagrees`);
    }
  }
});

// The 45 line is the axis the census is organised around, so it must fall on a
// band edge rather than inside one — otherwise the histogram and the under-45
// count could disagree.
test('the 45 line falls on an age-band edge', () => {
  assert.ok(HAGEBANDS.some((b) => b.lo === 45), 'no age band starts at 45');
  const under = HAGEBANDS.filter((b) => b.hi <= 45);
  const counted = HUMANS.filter((r) => r.age != null && under.some((b) => b.id === r.ageb)).length;
  assert.equal(counted, HUMANS.filter((r) => r.u45).length,
    'the under-45 age bands do not add up to the under-45 flag');
});

test('band edges are contiguous and cover the whole scope', () => {
  assert.equal(HBANDS[0].lo, 0.1);
  assert.equal(HBANDS[HBANDS.length - 1].hi, 5.0);
  for (let i = 1; i < HBANDS.length; i += 1) {
    assert.equal(HBANDS[i].lo, HBANDS[i - 1].hi, `band ${HBANDS[i].id} leaves a gap`);
  }
});

// Provenance is a claim about sourcing, so it should track the band: the census
// exists because published figures run out below $1B.
test('the sub-$1B half is not resting on published figures', () => {
  const small = HUMANS.filter((r) => r.nw < 1);
  assert.ok(small.length > 50, 'expected a substantial sub-$1B cohort');
  const reported = small.filter((r) => r.p === 'R').length;
  assert.ok(reported / small.length < 0.5,
    `${Math.round((reported / small.length) * 100)}% of sub-$1B records claim to be published, which is implausible`);
});
